// Code generated by go-swagger; DO NOT EDIT.

package task

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetProjectProjectIDTasksParams creates a new GetProjectProjectIDTasksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectProjectIDTasksParams() *GetProjectProjectIDTasksParams {
	return NewGetProjectProjectIDTasksParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetProjectProjectIDTasksParamsWithTimeout creates a new GetProjectProjectIDTasksParams object
// with the ability to set a timeout on a request.
func NewGetProjectProjectIDTasksParamsWithTimeout(timeout time.Duration) *GetProjectProjectIDTasksParams {
	return &GetProjectProjectIDTasksParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetProjectProjectIDTasksParamsWithContext creates a new GetProjectProjectIDTasksParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectProjectIDTasksParams].
func NewGetProjectProjectIDTasksParamsWithContext(ctx context.Context) *GetProjectProjectIDTasksParams {
	return &GetProjectProjectIDTasksParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetProjectProjectIDTasksParamsWithHTTPClient creates a new GetProjectProjectIDTasksParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectProjectIDTasksParamsWithHTTPClient(client *http.Client) *GetProjectProjectIDTasksParams {
	return &GetProjectProjectIDTasksParams{
		HTTPClient: client,
	}
}

/*
GetProjectProjectIDTasksParams contains all the parameters to send to the API endpoint

	for the get project project ID tasks operation.

	Typically these are written to a http.Request.
*/
type GetProjectProjectIDTasksParams struct {

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get project project ID tasks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectProjectIDTasksParams) WithDefaults() *GetProjectProjectIDTasksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get project project ID tasks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectProjectIDTasksParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get project project ID tasks params.
func (o *GetProjectProjectIDTasksParams) WithTimeout(timeout time.Duration) *GetProjectProjectIDTasksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project project ID tasks params.
func (o *GetProjectProjectIDTasksParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get project project ID tasks params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectProjectIDTasksParams].
func (o *GetProjectProjectIDTasksParams) WithContext(ctx context.Context) *GetProjectProjectIDTasksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project project ID tasks params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectProjectIDTasksParams].
func (o *GetProjectProjectIDTasksParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get project project ID tasks params.
func (o *GetProjectProjectIDTasksParams) WithHTTPClient(client *http.Client) *GetProjectProjectIDTasksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project project ID tasks params.
func (o *GetProjectProjectIDTasksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectID adds the projectID to the get project project ID tasks params.
func (o *GetProjectProjectIDTasksParams) WithProjectID(projectID int64) *GetProjectProjectIDTasksParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get project project ID tasks params.
func (o *GetProjectProjectIDTasksParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetProjectProjectIDTasksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param project_id
	if err := r.SetPathParam("project_id", conv.FormatInteger(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
