// Code generated by go-swagger; DO NOT EDIT.

package task

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetProjectProjectIDTasksTaskIDRawOutputReader is a Reader for the GetProjectProjectIDTasksTaskIDRawOutput structure.
type GetProjectProjectIDTasksTaskIDRawOutputReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectProjectIDTasksTaskIDRawOutputReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectProjectIDTasksTaskIDRawOutputOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /project/{project_id}/tasks/{task_id}/raw_output] GetProjectProjectIDTasksTaskIDRawOutput", response, response.Code())
	}
}

// NewGetProjectProjectIDTasksTaskIDRawOutputOK creates a GetProjectProjectIDTasksTaskIDRawOutputOK with default headers values
func NewGetProjectProjectIDTasksTaskIDRawOutputOK() *GetProjectProjectIDTasksTaskIDRawOutputOK {
	return &GetProjectProjectIDTasksTaskIDRawOutputOK{}
}

/*
GetProjectProjectIDTasksTaskIDRawOutputOK describes a response with status code 200, with default header values.

output
*/
type GetProjectProjectIDTasksTaskIDRawOutputOK struct {
	ContentType string
}

// IsSuccess returns true when this get project project Id tasks task Id raw output o k response has a 2xx status code
func (o *GetProjectProjectIDTasksTaskIDRawOutputOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get project project Id tasks task Id raw output o k response has a 3xx status code
func (o *GetProjectProjectIDTasksTaskIDRawOutputOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project project Id tasks task Id raw output o k response has a 4xx status code
func (o *GetProjectProjectIDTasksTaskIDRawOutputOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get project project Id tasks task Id raw output o k response has a 5xx status code
func (o *GetProjectProjectIDTasksTaskIDRawOutputOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get project project Id tasks task Id raw output o k response a status code equal to that given
func (o *GetProjectProjectIDTasksTaskIDRawOutputOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get project project Id tasks task Id raw output o k response
func (o *GetProjectProjectIDTasksTaskIDRawOutputOK) Code() int {
	return 200
}

func (o *GetProjectProjectIDTasksTaskIDRawOutputOK) Error() string {
	return fmt.Sprintf("[GET /project/{project_id}/tasks/{task_id}/raw_output][%d] getProjectProjectIdTasksTaskIdRawOutputOK", 200)
}

func (o *GetProjectProjectIDTasksTaskIDRawOutputOK) String() string {
	return fmt.Sprintf("[GET /project/{project_id}/tasks/{task_id}/raw_output][%d] getProjectProjectIdTasksTaskIdRawOutputOK", 200)
}

func (o *GetProjectProjectIDTasksTaskIDRawOutputOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header content-type
	hdrContentType := response.GetHeader("content-type")

	if hdrContentType != "" {
		o.ContentType = hdrContentType
	}

	return nil
}
