// Code generated by go-swagger; DO NOT EDIT.

package task

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"terraform-provider-semaphoreui/semaphoreui/models"
)

// GetProjectProjectIDTasksTaskIDOutputReader is a Reader for the GetProjectProjectIDTasksTaskIDOutput structure.
type GetProjectProjectIDTasksTaskIDOutputReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectProjectIDTasksTaskIDOutputReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectProjectIDTasksTaskIDOutputOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /project/{project_id}/tasks/{task_id}/output] GetProjectProjectIDTasksTaskIDOutput", response, response.Code())
	}
}

// NewGetProjectProjectIDTasksTaskIDOutputOK creates a GetProjectProjectIDTasksTaskIDOutputOK with default headers values
func NewGetProjectProjectIDTasksTaskIDOutputOK() *GetProjectProjectIDTasksTaskIDOutputOK {
	return &GetProjectProjectIDTasksTaskIDOutputOK{}
}

/*
GetProjectProjectIDTasksTaskIDOutputOK describes a response with status code 200, with default header values.

output
*/
type GetProjectProjectIDTasksTaskIDOutputOK struct {
	Payload []*models.TaskOutput
}

// IsSuccess returns true when this get project project Id tasks task Id output o k response has a 2xx status code
func (o *GetProjectProjectIDTasksTaskIDOutputOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get project project Id tasks task Id output o k response has a 3xx status code
func (o *GetProjectProjectIDTasksTaskIDOutputOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project project Id tasks task Id output o k response has a 4xx status code
func (o *GetProjectProjectIDTasksTaskIDOutputOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get project project Id tasks task Id output o k response has a 5xx status code
func (o *GetProjectProjectIDTasksTaskIDOutputOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get project project Id tasks task Id output o k response a status code equal to that given
func (o *GetProjectProjectIDTasksTaskIDOutputOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get project project Id tasks task Id output o k response
func (o *GetProjectProjectIDTasksTaskIDOutputOK) Code() int {
	return 200
}

func (o *GetProjectProjectIDTasksTaskIDOutputOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{project_id}/tasks/{task_id}/output][%d] getProjectProjectIdTasksTaskIdOutputOK %s", 200, payload)
}

func (o *GetProjectProjectIDTasksTaskIDOutputOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{project_id}/tasks/{task_id}/output][%d] getProjectProjectIdTasksTaskIdOutputOK %s", 200, payload)
}

func (o *GetProjectProjectIDTasksTaskIDOutputOK) GetPayload() []*models.TaskOutput {
	return o.Payload
}

func (o *GetProjectProjectIDTasksTaskIDOutputOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
