// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ClusterTaskRecord cluster task record
//
// swagger:model ClusterTaskRecord
type ClusterTaskRecord struct {

	// alias
	Alias string `json:"alias,omitempty"`

	// owning node, empty if unknown
	NodeID string `json:"node_id,omitempty"`

	// project id
	ProjectID int64 `json:"project_id,omitempty"`

	// runner id
	RunnerID int64 `json:"runner_id,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// task id
	TaskID int64 `json:"task_id,omitempty"`

	// template id
	TemplateID int64 `json:"template_id,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this cluster task record
func (m *ClusterTaskRecord) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cluster task record based on context it is used
func (m *ClusterTaskRecord) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClusterTaskRecord) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterTaskRecord) UnmarshalBinary(b []byte) error {
	var res ClusterTaskRecord
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
