// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InfoType info type
//
// swagger:model InfoType
type InfoType struct {

	// ansible
	Ansible string `json:"ansible,omitempty"`

	// auth methods
	AuthMethods any `json:"auth_methods,omitempty"`

	// git client
	GitClient string `json:"git_client,omitempty"`

	// premium features
	PremiumFeatures any `json:"premium_features,omitempty"`

	// schedule timezone
	ScheduleTimezone string `json:"schedule_timezone,omitempty"`

	// use remote runner
	UseRemoteRunner bool `json:"use_remote_runner,omitempty"`

	// version
	Version string `json:"version,omitempty"`

	// web host
	WebHost string `json:"web_host,omitempty"`
}

// Validate validates this info type
func (m *InfoType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this info type based on context it is used
func (m *InfoType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InfoType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InfoType) UnmarshalBinary(b []byte) error {
	var res InfoType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
