// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IntegrationAlias integration alias
//
// swagger:model IntegrationAlias
type IntegrationAlias struct {

	// id
	ID int64 `json:"id,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this integration alias
func (m *IntegrationAlias) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this integration alias based on context it is used
func (m *IntegrationAlias) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IntegrationAlias) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IntegrationAlias) UnmarshalBinary(b []byte) error {
	var res IntegrationAlias
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
