// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Schedule schedule
//
// swagger:model Schedule
type Schedule struct {

	// active
	Active bool `json:"active,omitempty"`

	// cron format
	CronFormat string `json:"cron_format,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// project id
	ProjectID int64 `json:"project_id,omitempty"`

	// run at
	// Format: date-time
	RunAt strfmt.DateTime `json:"run_at,omitempty"`

	// task params
	TaskParams *TaskPrams `json:"task_params,omitempty"`

	// template id
	TemplateID int64 `json:"template_id,omitempty"`

	// type
	// Enum: ["","run_at"]
	Type string `json:"type,omitempty"`
}

// Validate validates this schedule
func (m *Schedule) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRunAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTaskParams(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Schedule) validateRunAt(formats strfmt.Registry) error {
	if swag.IsZero(m.RunAt) { // not required
		return nil
	}

	if err := validate.FormatOf("run_at", "body", "date-time", m.RunAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Schedule) validateTaskParams(formats strfmt.Registry) error {
	if swag.IsZero(m.TaskParams) { // not required
		return nil
	}

	if m.TaskParams != nil {
		if err := m.TaskParams.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("task_params")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("task_params")
			}

			return err
		}
	}

	return nil
}

var scheduleTypeTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["","run_at"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		scheduleTypeTypePropEnum = append(scheduleTypeTypePropEnum, v)
	}
}

const (

	// ScheduleTypeEmpty captures enum value ""
	ScheduleTypeEmpty string = ""

	// ScheduleTypeRunAt captures enum value "run_at"
	ScheduleTypeRunAt string = "run_at"
)

// prop value enum
func (m *Schedule) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, scheduleTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Schedule) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this schedule based on the context it is used
func (m *Schedule) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTaskParams(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Schedule) contextValidateTaskParams(ctx context.Context, formats strfmt.Registry) error {

	if m.TaskParams != nil {

		if swag.IsZero(m.TaskParams) { // not required
			return nil
		}

		if err := m.TaskParams.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("task_params")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("task_params")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Schedule) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Schedule) UnmarshalBinary(b []byte) error {
	var res Schedule
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
