// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Task task
//
// swagger:model Task
type Task struct {

	// arguments
	Arguments string `json:"arguments,omitempty"`

	// environment
	Environment string `json:"environment,omitempty"`

	// git branch
	GitBranch string `json:"git_branch,omitempty"`

	// id
	// Example: 23
	ID int64 `json:"id,omitempty"`

	// inventory id
	InventoryID int64 `json:"inventory_id,omitempty"`

	// limit
	Limit string `json:"limit,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// params
	Params struct {
		AnsibleTaskParams

		TerraformTaskParams
	} `json:"params,omitempty"`

	// playbook
	Playbook string `json:"playbook,omitempty"`

	// secret
	Secret string `json:"secret,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// template id
	TemplateID int64 `json:"template_id,omitempty"`
}

// Validate validates this task
func (m *Task) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateParams(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Task) validateParams(formats strfmt.Registry) error {
	if swag.IsZero(m.Params) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this task based on the context it is used
func (m *Task) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateParams(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Task) contextValidateParams(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *Task) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Task) UnmarshalBinary(b []byte) error {
	var res Task
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
