// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TemplateVault template vault
//
// swagger:model TemplateVault
type TemplateVault struct {

	// id
	ID int64 `json:"id,omitempty"`

	// name
	// Example: default
	Name string `json:"name,omitempty"`

	// script
	// Example: path/to/script-client.py
	Script string `json:"script,omitempty"`

	// type
	// Example: script
	// Enum: ["password","script"]
	Type string `json:"type,omitempty"`

	// vault key id
	VaultKeyID int64 `json:"vault_key_id,omitempty"`
}

// Validate validates this template vault
func (m *TemplateVault) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var templateVaultTypeTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["password","script"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		templateVaultTypeTypePropEnum = append(templateVaultTypeTypePropEnum, v)
	}
}

const (

	// TemplateVaultTypePassword captures enum value "password"
	TemplateVaultTypePassword string = "password"

	// TemplateVaultTypeScript captures enum value "script"
	TemplateVaultTypeScript string = "script"
)

// prop value enum
func (m *TemplateVault) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, templateVaultTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *TemplateVault) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this template vault based on context it is used
func (m *TemplateVault) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TemplateVault) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TemplateVault) UnmarshalBinary(b []byte) error {
	var res TemplateVault
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
