// Code generated by go-swagger; DO NOT EDIT.

package template

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewDeleteProjectProjectIDTemplatesTemplateIDParams creates a new DeleteProjectProjectIDTemplatesTemplateIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteProjectProjectIDTemplatesTemplateIDParams() *DeleteProjectProjectIDTemplatesTemplateIDParams {
	return NewDeleteProjectProjectIDTemplatesTemplateIDParamsWithTimeout(cr.DefaultTimeout)
}

// NewDeleteProjectProjectIDTemplatesTemplateIDParamsWithTimeout creates a new DeleteProjectProjectIDTemplatesTemplateIDParams object
// with the ability to set a timeout on a request.
func NewDeleteProjectProjectIDTemplatesTemplateIDParamsWithTimeout(timeout time.Duration) *DeleteProjectProjectIDTemplatesTemplateIDParams {
	return &DeleteProjectProjectIDTemplatesTemplateIDParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDeleteProjectProjectIDTemplatesTemplateIDParamsWithContext creates a new DeleteProjectProjectIDTemplatesTemplateIDParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteProjectProjectIDTemplatesTemplateIDParams].
func NewDeleteProjectProjectIDTemplatesTemplateIDParamsWithContext(ctx context.Context) *DeleteProjectProjectIDTemplatesTemplateIDParams {
	return &DeleteProjectProjectIDTemplatesTemplateIDParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDeleteProjectProjectIDTemplatesTemplateIDParamsWithHTTPClient creates a new DeleteProjectProjectIDTemplatesTemplateIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteProjectProjectIDTemplatesTemplateIDParamsWithHTTPClient(client *http.Client) *DeleteProjectProjectIDTemplatesTemplateIDParams {
	return &DeleteProjectProjectIDTemplatesTemplateIDParams{
		HTTPClient: client,
	}
}

/*
DeleteProjectProjectIDTemplatesTemplateIDParams contains all the parameters to send to the API endpoint

	for the delete project project ID templates template ID operation.

	Typically these are written to a http.Request.
*/
type DeleteProjectProjectIDTemplatesTemplateIDParams struct {

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	/* TemplateID.

	   template ID
	*/
	TemplateID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the delete project project ID templates template ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectProjectIDTemplatesTemplateIDParams) WithDefaults() *DeleteProjectProjectIDTemplatesTemplateIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete project project ID templates template ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectProjectIDTemplatesTemplateIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete project project ID templates template ID params.
func (o *DeleteProjectProjectIDTemplatesTemplateIDParams) WithTimeout(timeout time.Duration) *DeleteProjectProjectIDTemplatesTemplateIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete project project ID templates template ID params.
func (o *DeleteProjectProjectIDTemplatesTemplateIDParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the delete project project ID templates template ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteProjectProjectIDTemplatesTemplateIDParams].
func (o *DeleteProjectProjectIDTemplatesTemplateIDParams) WithContext(ctx context.Context) *DeleteProjectProjectIDTemplatesTemplateIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete project project ID templates template ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteProjectProjectIDTemplatesTemplateIDParams].
func (o *DeleteProjectProjectIDTemplatesTemplateIDParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the delete project project ID templates template ID params.
func (o *DeleteProjectProjectIDTemplatesTemplateIDParams) WithHTTPClient(client *http.Client) *DeleteProjectProjectIDTemplatesTemplateIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete project project ID templates template ID params.
func (o *DeleteProjectProjectIDTemplatesTemplateIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectID adds the projectID to the delete project project ID templates template ID params.
func (o *DeleteProjectProjectIDTemplatesTemplateIDParams) WithProjectID(projectID int64) *DeleteProjectProjectIDTemplatesTemplateIDParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the delete project project ID templates template ID params.
func (o *DeleteProjectProjectIDTemplatesTemplateIDParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WithTemplateID adds the templateID to the delete project project ID templates template ID params.
func (o *DeleteProjectProjectIDTemplatesTemplateIDParams) WithTemplateID(templateID int64) *DeleteProjectProjectIDTemplatesTemplateIDParams {
	o.SetTemplateID(templateID)
	return o
}

// SetTemplateID adds the templateId to the delete project project ID templates template ID params.
func (o *DeleteProjectProjectIDTemplatesTemplateIDParams) SetTemplateID(templateID int64) {
	o.TemplateID = templateID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DeleteProjectProjectIDTemplatesTemplateIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param project_id
	if err := r.SetPathParam("project_id", conv.FormatInteger(o.ProjectID)); err != nil {
		return err
	}

	// path param template_id
	if err := r.SetPathParam("template_id", conv.FormatInteger(o.TemplateID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
