// Code generated by go-swagger; DO NOT EDIT.

package template

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetProjectProjectIDTemplatesParams creates a new GetProjectProjectIDTemplatesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectProjectIDTemplatesParams() *GetProjectProjectIDTemplatesParams {
	return &GetProjectProjectIDTemplatesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProjectProjectIDTemplatesParamsWithTimeout creates a new GetProjectProjectIDTemplatesParams object
// with the ability to set a timeout on a request.
func NewGetProjectProjectIDTemplatesParamsWithTimeout(timeout time.Duration) *GetProjectProjectIDTemplatesParams {
	return &GetProjectProjectIDTemplatesParams{
		timeout: timeout,
	}
}

// NewGetProjectProjectIDTemplatesParamsWithContext creates a new GetProjectProjectIDTemplatesParams object
// with the ability to set a context for a request.
func NewGetProjectProjectIDTemplatesParamsWithContext(ctx context.Context) *GetProjectProjectIDTemplatesParams {
	return &GetProjectProjectIDTemplatesParams{
		Context: ctx,
	}
}

// NewGetProjectProjectIDTemplatesParamsWithHTTPClient creates a new GetProjectProjectIDTemplatesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectProjectIDTemplatesParamsWithHTTPClient(client *http.Client) *GetProjectProjectIDTemplatesParams {
	return &GetProjectProjectIDTemplatesParams{
		HTTPClient: client,
	}
}

/*
GetProjectProjectIDTemplatesParams contains all the parameters to send to the API endpoint

	for the get project project ID templates operation.

	Typically these are written to a http.Request.
*/
type GetProjectProjectIDTemplatesParams struct {

	/* Order.

	   ordering manner
	*/
	Order string

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	/* Sort.

	   sorting name
	*/
	Sort string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get project project ID templates params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectProjectIDTemplatesParams) WithDefaults() *GetProjectProjectIDTemplatesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get project project ID templates params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectProjectIDTemplatesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get project project ID templates params
func (o *GetProjectProjectIDTemplatesParams) WithTimeout(timeout time.Duration) *GetProjectProjectIDTemplatesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project project ID templates params
func (o *GetProjectProjectIDTemplatesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get project project ID templates params
func (o *GetProjectProjectIDTemplatesParams) WithContext(ctx context.Context) *GetProjectProjectIDTemplatesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project project ID templates params
func (o *GetProjectProjectIDTemplatesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get project project ID templates params
func (o *GetProjectProjectIDTemplatesParams) WithHTTPClient(client *http.Client) *GetProjectProjectIDTemplatesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project project ID templates params
func (o *GetProjectProjectIDTemplatesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrder adds the order to the get project project ID templates params
func (o *GetProjectProjectIDTemplatesParams) WithOrder(order string) *GetProjectProjectIDTemplatesParams {
	o.SetOrder(order)
	return o
}

// SetOrder adds the order to the get project project ID templates params
func (o *GetProjectProjectIDTemplatesParams) SetOrder(order string) {
	o.Order = order
}

// WithProjectID adds the projectID to the get project project ID templates params
func (o *GetProjectProjectIDTemplatesParams) WithProjectID(projectID int64) *GetProjectProjectIDTemplatesParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get project project ID templates params
func (o *GetProjectProjectIDTemplatesParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WithSort adds the sort to the get project project ID templates params
func (o *GetProjectProjectIDTemplatesParams) WithSort(sort string) *GetProjectProjectIDTemplatesParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the get project project ID templates params
func (o *GetProjectProjectIDTemplatesParams) SetSort(sort string) {
	o.Sort = sort
}

// WriteToRequest writes these params to a swagger request
func (o *GetProjectProjectIDTemplatesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param order
	qrOrder := o.Order
	qOrder := qrOrder
	if qOrder != "" {

		if err := r.SetQueryParam("order", qOrder); err != nil {
			return err
		}
	}

	// path param project_id
	if err := r.SetPathParam("project_id", swag.FormatInt64(o.ProjectID)); err != nil {
		return err
	}

	// query param sort
	qrSort := o.Sort
	qSort := qrSort
	if qSort != "" {

		if err := r.SetQueryParam("sort", qSort); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
