// Code generated by go-swagger; DO NOT EDIT.

package project

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteProjectProjectIDViewsViewIDParams creates a new DeleteProjectProjectIDViewsViewIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteProjectProjectIDViewsViewIDParams() *DeleteProjectProjectIDViewsViewIDParams {
	return &DeleteProjectProjectIDViewsViewIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteProjectProjectIDViewsViewIDParamsWithTimeout creates a new DeleteProjectProjectIDViewsViewIDParams object
// with the ability to set a timeout on a request.
func NewDeleteProjectProjectIDViewsViewIDParamsWithTimeout(timeout time.Duration) *DeleteProjectProjectIDViewsViewIDParams {
	return &DeleteProjectProjectIDViewsViewIDParams{
		timeout: timeout,
	}
}

// NewDeleteProjectProjectIDViewsViewIDParamsWithContext creates a new DeleteProjectProjectIDViewsViewIDParams object
// with the ability to set a context for a request.
func NewDeleteProjectProjectIDViewsViewIDParamsWithContext(ctx context.Context) *DeleteProjectProjectIDViewsViewIDParams {
	return &DeleteProjectProjectIDViewsViewIDParams{
		Context: ctx,
	}
}

// NewDeleteProjectProjectIDViewsViewIDParamsWithHTTPClient creates a new DeleteProjectProjectIDViewsViewIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteProjectProjectIDViewsViewIDParamsWithHTTPClient(client *http.Client) *DeleteProjectProjectIDViewsViewIDParams {
	return &DeleteProjectProjectIDViewsViewIDParams{
		HTTPClient: client,
	}
}

/*
DeleteProjectProjectIDViewsViewIDParams contains all the parameters to send to the API endpoint

	for the delete project project ID views view ID operation.

	Typically these are written to a http.Request.
*/
type DeleteProjectProjectIDViewsViewIDParams struct {

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	/* ViewID.

	   view ID
	*/
	ViewID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete project project ID views view ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectProjectIDViewsViewIDParams) WithDefaults() *DeleteProjectProjectIDViewsViewIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete project project ID views view ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectProjectIDViewsViewIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete project project ID views view ID params
func (o *DeleteProjectProjectIDViewsViewIDParams) WithTimeout(timeout time.Duration) *DeleteProjectProjectIDViewsViewIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete project project ID views view ID params
func (o *DeleteProjectProjectIDViewsViewIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete project project ID views view ID params
func (o *DeleteProjectProjectIDViewsViewIDParams) WithContext(ctx context.Context) *DeleteProjectProjectIDViewsViewIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete project project ID views view ID params
func (o *DeleteProjectProjectIDViewsViewIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete project project ID views view ID params
func (o *DeleteProjectProjectIDViewsViewIDParams) WithHTTPClient(client *http.Client) *DeleteProjectProjectIDViewsViewIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete project project ID views view ID params
func (o *DeleteProjectProjectIDViewsViewIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectID adds the projectID to the delete project project ID views view ID params
func (o *DeleteProjectProjectIDViewsViewIDParams) WithProjectID(projectID int64) *DeleteProjectProjectIDViewsViewIDParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the delete project project ID views view ID params
func (o *DeleteProjectProjectIDViewsViewIDParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WithViewID adds the viewID to the delete project project ID views view ID params
func (o *DeleteProjectProjectIDViewsViewIDParams) WithViewID(viewID int64) *DeleteProjectProjectIDViewsViewIDParams {
	o.SetViewID(viewID)
	return o
}

// SetViewID adds the viewId to the delete project project ID views view ID params
func (o *DeleteProjectProjectIDViewsViewIDParams) SetViewID(viewID int64) {
	o.ViewID = viewID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteProjectProjectIDViewsViewIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param project_id
	if err := r.SetPathParam("project_id", swag.FormatInt64(o.ProjectID)); err != nil {
		return err
	}

	// path param view_id
	if err := r.SetPathParam("view_id", swag.FormatInt64(o.ViewID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
