// Code generated by go-swagger; DO NOT EDIT.

package project

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteProjectProjectIDUsersUserIDReader is a Reader for the DeleteProjectProjectIDUsersUserID structure.
type DeleteProjectProjectIDUsersUserIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProjectProjectIDUsersUserIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteProjectProjectIDUsersUserIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /project/{project_id}/users/{user_id}] DeleteProjectProjectIDUsersUserID", response, response.Code())
	}
}

// NewDeleteProjectProjectIDUsersUserIDNoContent creates a DeleteProjectProjectIDUsersUserIDNoContent with default headers values
func NewDeleteProjectProjectIDUsersUserIDNoContent() *DeleteProjectProjectIDUsersUserIDNoContent {
	return &DeleteProjectProjectIDUsersUserIDNoContent{}
}

/*
DeleteProjectProjectIDUsersUserIDNoContent describes a response with status code 204, with default header values.

User removed
*/
type DeleteProjectProjectIDUsersUserIDNoContent struct {
}

// IsSuccess returns true when this delete project project Id users user Id no content response has a 2xx status code
func (o *DeleteProjectProjectIDUsersUserIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete project project Id users user Id no content response has a 3xx status code
func (o *DeleteProjectProjectIDUsersUserIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete project project Id users user Id no content response has a 4xx status code
func (o *DeleteProjectProjectIDUsersUserIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete project project Id users user Id no content response has a 5xx status code
func (o *DeleteProjectProjectIDUsersUserIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete project project Id users user Id no content response a status code equal to that given
func (o *DeleteProjectProjectIDUsersUserIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete project project Id users user Id no content response
func (o *DeleteProjectProjectIDUsersUserIDNoContent) Code() int {
	return 204
}

func (o *DeleteProjectProjectIDUsersUserIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /project/{project_id}/users/{user_id}][%d] deleteProjectProjectIdUsersUserIdNoContent", 204)
}

func (o *DeleteProjectProjectIDUsersUserIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /project/{project_id}/users/{user_id}][%d] deleteProjectProjectIdUsersUserIdNoContent", 204)
}

func (o *DeleteProjectProjectIDUsersUserIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
