// Code generated by go-swagger; DO NOT EDIT.

package project

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"terraform-provider-semaphoreui/semaphoreui/models"
)

// GetProjectProjectIDEventsReader is a Reader for the GetProjectProjectIDEvents structure.
type GetProjectProjectIDEventsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectProjectIDEventsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectProjectIDEventsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /project/{project_id}/events] GetProjectProjectIDEvents", response, response.Code())
	}
}

// NewGetProjectProjectIDEventsOK creates a GetProjectProjectIDEventsOK with default headers values
func NewGetProjectProjectIDEventsOK() *GetProjectProjectIDEventsOK {
	return &GetProjectProjectIDEventsOK{}
}

/*
GetProjectProjectIDEventsOK describes a response with status code 200, with default header values.

Array of events in chronological order
*/
type GetProjectProjectIDEventsOK struct {
	Payload []*models.Event
}

// IsSuccess returns true when this get project project Id events o k response has a 2xx status code
func (o *GetProjectProjectIDEventsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get project project Id events o k response has a 3xx status code
func (o *GetProjectProjectIDEventsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project project Id events o k response has a 4xx status code
func (o *GetProjectProjectIDEventsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get project project Id events o k response has a 5xx status code
func (o *GetProjectProjectIDEventsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get project project Id events o k response a status code equal to that given
func (o *GetProjectProjectIDEventsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get project project Id events o k response
func (o *GetProjectProjectIDEventsOK) Code() int {
	return 200
}

func (o *GetProjectProjectIDEventsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{project_id}/events][%d] getProjectProjectIdEventsOK %s", 200, payload)
}

func (o *GetProjectProjectIDEventsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{project_id}/events][%d] getProjectProjectIdEventsOK %s", 200, payload)
}

func (o *GetProjectProjectIDEventsOK) GetPayload() []*models.Event {
	return o.Payload
}

func (o *GetProjectProjectIDEventsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
