// Code generated by go-swagger; DO NOT EDIT.

package project

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetProjectProjectIDUsersParams creates a new GetProjectProjectIDUsersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectProjectIDUsersParams() *GetProjectProjectIDUsersParams {
	return &GetProjectProjectIDUsersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProjectProjectIDUsersParamsWithTimeout creates a new GetProjectProjectIDUsersParams object
// with the ability to set a timeout on a request.
func NewGetProjectProjectIDUsersParamsWithTimeout(timeout time.Duration) *GetProjectProjectIDUsersParams {
	return &GetProjectProjectIDUsersParams{
		timeout: timeout,
	}
}

// NewGetProjectProjectIDUsersParamsWithContext creates a new GetProjectProjectIDUsersParams object
// with the ability to set a context for a request.
func NewGetProjectProjectIDUsersParamsWithContext(ctx context.Context) *GetProjectProjectIDUsersParams {
	return &GetProjectProjectIDUsersParams{
		Context: ctx,
	}
}

// NewGetProjectProjectIDUsersParamsWithHTTPClient creates a new GetProjectProjectIDUsersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectProjectIDUsersParamsWithHTTPClient(client *http.Client) *GetProjectProjectIDUsersParams {
	return &GetProjectProjectIDUsersParams{
		HTTPClient: client,
	}
}

/*
GetProjectProjectIDUsersParams contains all the parameters to send to the API endpoint

	for the get project project ID users operation.

	Typically these are written to a http.Request.
*/
type GetProjectProjectIDUsersParams struct {

	/* Order.

	   ordering manner
	*/
	Order string

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	/* Sort.

	   sorting name
	*/
	Sort string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get project project ID users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectProjectIDUsersParams) WithDefaults() *GetProjectProjectIDUsersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get project project ID users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectProjectIDUsersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get project project ID users params
func (o *GetProjectProjectIDUsersParams) WithTimeout(timeout time.Duration) *GetProjectProjectIDUsersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project project ID users params
func (o *GetProjectProjectIDUsersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get project project ID users params
func (o *GetProjectProjectIDUsersParams) WithContext(ctx context.Context) *GetProjectProjectIDUsersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project project ID users params
func (o *GetProjectProjectIDUsersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get project project ID users params
func (o *GetProjectProjectIDUsersParams) WithHTTPClient(client *http.Client) *GetProjectProjectIDUsersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project project ID users params
func (o *GetProjectProjectIDUsersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrder adds the order to the get project project ID users params
func (o *GetProjectProjectIDUsersParams) WithOrder(order string) *GetProjectProjectIDUsersParams {
	o.SetOrder(order)
	return o
}

// SetOrder adds the order to the get project project ID users params
func (o *GetProjectProjectIDUsersParams) SetOrder(order string) {
	o.Order = order
}

// WithProjectID adds the projectID to the get project project ID users params
func (o *GetProjectProjectIDUsersParams) WithProjectID(projectID int64) *GetProjectProjectIDUsersParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get project project ID users params
func (o *GetProjectProjectIDUsersParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WithSort adds the sort to the get project project ID users params
func (o *GetProjectProjectIDUsersParams) WithSort(sort string) *GetProjectProjectIDUsersParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the get project project ID users params
func (o *GetProjectProjectIDUsersParams) SetSort(sort string) {
	o.Sort = sort
}

// WriteToRequest writes these params to a swagger request
func (o *GetProjectProjectIDUsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param order
	qrOrder := o.Order
	qOrder := qrOrder
	if qOrder != "" {

		if err := r.SetQueryParam("order", qOrder); err != nil {
			return err
		}
	}

	// path param project_id
	if err := r.SetPathParam("project_id", swag.FormatInt64(o.ProjectID)); err != nil {
		return err
	}

	// query param sort
	qrSort := o.Sort
	qSort := qrSort
	if qSort != "" {

		if err := r.SetQueryParam("sort", qSort); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
