// Code generated by go-swagger; DO NOT EDIT.

package project

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetProjectProjectIDViewsParams creates a new GetProjectProjectIDViewsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectProjectIDViewsParams() *GetProjectProjectIDViewsParams {
	return &GetProjectProjectIDViewsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProjectProjectIDViewsParamsWithTimeout creates a new GetProjectProjectIDViewsParams object
// with the ability to set a timeout on a request.
func NewGetProjectProjectIDViewsParamsWithTimeout(timeout time.Duration) *GetProjectProjectIDViewsParams {
	return &GetProjectProjectIDViewsParams{
		timeout: timeout,
	}
}

// NewGetProjectProjectIDViewsParamsWithContext creates a new GetProjectProjectIDViewsParams object
// with the ability to set a context for a request.
func NewGetProjectProjectIDViewsParamsWithContext(ctx context.Context) *GetProjectProjectIDViewsParams {
	return &GetProjectProjectIDViewsParams{
		Context: ctx,
	}
}

// NewGetProjectProjectIDViewsParamsWithHTTPClient creates a new GetProjectProjectIDViewsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectProjectIDViewsParamsWithHTTPClient(client *http.Client) *GetProjectProjectIDViewsParams {
	return &GetProjectProjectIDViewsParams{
		HTTPClient: client,
	}
}

/*
GetProjectProjectIDViewsParams contains all the parameters to send to the API endpoint

	for the get project project ID views operation.

	Typically these are written to a http.Request.
*/
type GetProjectProjectIDViewsParams struct {

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get project project ID views params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectProjectIDViewsParams) WithDefaults() *GetProjectProjectIDViewsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get project project ID views params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectProjectIDViewsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get project project ID views params
func (o *GetProjectProjectIDViewsParams) WithTimeout(timeout time.Duration) *GetProjectProjectIDViewsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project project ID views params
func (o *GetProjectProjectIDViewsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get project project ID views params
func (o *GetProjectProjectIDViewsParams) WithContext(ctx context.Context) *GetProjectProjectIDViewsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project project ID views params
func (o *GetProjectProjectIDViewsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get project project ID views params
func (o *GetProjectProjectIDViewsParams) WithHTTPClient(client *http.Client) *GetProjectProjectIDViewsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project project ID views params
func (o *GetProjectProjectIDViewsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectID adds the projectID to the get project project ID views params
func (o *GetProjectProjectIDViewsParams) WithProjectID(projectID int64) *GetProjectProjectIDViewsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get project project ID views params
func (o *GetProjectProjectIDViewsParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *GetProjectProjectIDViewsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param project_id
	if err := r.SetPathParam("project_id", swag.FormatInt64(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
