// Code generated by go-swagger; DO NOT EDIT.

package project

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetProjectProjectIDParams creates a new GetProjectProjectIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectProjectIDParams() *GetProjectProjectIDParams {
	return NewGetProjectProjectIDParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetProjectProjectIDParamsWithTimeout creates a new GetProjectProjectIDParams object
// with the ability to set a timeout on a request.
func NewGetProjectProjectIDParamsWithTimeout(timeout time.Duration) *GetProjectProjectIDParams {
	return &GetProjectProjectIDParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetProjectProjectIDParamsWithContext creates a new GetProjectProjectIDParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectProjectIDParams].
func NewGetProjectProjectIDParamsWithContext(ctx context.Context) *GetProjectProjectIDParams {
	return &GetProjectProjectIDParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetProjectProjectIDParamsWithHTTPClient creates a new GetProjectProjectIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectProjectIDParamsWithHTTPClient(client *http.Client) *GetProjectProjectIDParams {
	return &GetProjectProjectIDParams{
		HTTPClient: client,
	}
}

/*
GetProjectProjectIDParams contains all the parameters to send to the API endpoint

	for the get project project ID operation.

	Typically these are written to a http.Request.
*/
type GetProjectProjectIDParams struct {

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get project project ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectProjectIDParams) WithDefaults() *GetProjectProjectIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get project project ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectProjectIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get project project ID params.
func (o *GetProjectProjectIDParams) WithTimeout(timeout time.Duration) *GetProjectProjectIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project project ID params.
func (o *GetProjectProjectIDParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get project project ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectProjectIDParams].
func (o *GetProjectProjectIDParams) WithContext(ctx context.Context) *GetProjectProjectIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project project ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectProjectIDParams].
func (o *GetProjectProjectIDParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get project project ID params.
func (o *GetProjectProjectIDParams) WithHTTPClient(client *http.Client) *GetProjectProjectIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project project ID params.
func (o *GetProjectProjectIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectID adds the projectID to the get project project ID params.
func (o *GetProjectProjectIDParams) WithProjectID(projectID int64) *GetProjectProjectIDParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get project project ID params.
func (o *GetProjectProjectIDParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetProjectProjectIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param project_id
	if err := r.SetPathParam("project_id", conv.FormatInteger(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
