// Code generated by go-swagger; DO NOT EDIT.

package project

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPutProjectProjectIDParams creates a new PutProjectProjectIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutProjectProjectIDParams() *PutProjectProjectIDParams {
	return &PutProjectProjectIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutProjectProjectIDParamsWithTimeout creates a new PutProjectProjectIDParams object
// with the ability to set a timeout on a request.
func NewPutProjectProjectIDParamsWithTimeout(timeout time.Duration) *PutProjectProjectIDParams {
	return &PutProjectProjectIDParams{
		timeout: timeout,
	}
}

// NewPutProjectProjectIDParamsWithContext creates a new PutProjectProjectIDParams object
// with the ability to set a context for a request.
func NewPutProjectProjectIDParamsWithContext(ctx context.Context) *PutProjectProjectIDParams {
	return &PutProjectProjectIDParams{
		Context: ctx,
	}
}

// NewPutProjectProjectIDParamsWithHTTPClient creates a new PutProjectProjectIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutProjectProjectIDParamsWithHTTPClient(client *http.Client) *PutProjectProjectIDParams {
	return &PutProjectProjectIDParams{
		HTTPClient: client,
	}
}

/*
PutProjectProjectIDParams contains all the parameters to send to the API endpoint

	for the put project project ID operation.

	Typically these are written to a http.Request.
*/
type PutProjectProjectIDParams struct {

	// Project.
	Project PutProjectProjectIDBody

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put project project ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProjectProjectIDParams) WithDefaults() *PutProjectProjectIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put project project ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProjectProjectIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put project project ID params
func (o *PutProjectProjectIDParams) WithTimeout(timeout time.Duration) *PutProjectProjectIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put project project ID params
func (o *PutProjectProjectIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put project project ID params
func (o *PutProjectProjectIDParams) WithContext(ctx context.Context) *PutProjectProjectIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put project project ID params
func (o *PutProjectProjectIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put project project ID params
func (o *PutProjectProjectIDParams) WithHTTPClient(client *http.Client) *PutProjectProjectIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put project project ID params
func (o *PutProjectProjectIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProject adds the project to the put project project ID params
func (o *PutProjectProjectIDParams) WithProject(project PutProjectProjectIDBody) *PutProjectProjectIDParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the put project project ID params
func (o *PutProjectProjectIDParams) SetProject(project PutProjectProjectIDBody) {
	o.Project = project
}

// WithProjectID adds the projectID to the put project project ID params
func (o *PutProjectProjectIDParams) WithProjectID(projectID int64) *PutProjectProjectIDParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the put project project ID params
func (o *PutProjectProjectIDParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *PutProjectProjectIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Project); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", swag.FormatInt64(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
