// Code generated by go-swagger; DO NOT EDIT.

package runner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetProjectProjectIDRunnerTagsParams creates a new GetProjectProjectIDRunnerTagsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectProjectIDRunnerTagsParams() *GetProjectProjectIDRunnerTagsParams {
	return &GetProjectProjectIDRunnerTagsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProjectProjectIDRunnerTagsParamsWithTimeout creates a new GetProjectProjectIDRunnerTagsParams object
// with the ability to set a timeout on a request.
func NewGetProjectProjectIDRunnerTagsParamsWithTimeout(timeout time.Duration) *GetProjectProjectIDRunnerTagsParams {
	return &GetProjectProjectIDRunnerTagsParams{
		timeout: timeout,
	}
}

// NewGetProjectProjectIDRunnerTagsParamsWithContext creates a new GetProjectProjectIDRunnerTagsParams object
// with the ability to set a context for a request.
func NewGetProjectProjectIDRunnerTagsParamsWithContext(ctx context.Context) *GetProjectProjectIDRunnerTagsParams {
	return &GetProjectProjectIDRunnerTagsParams{
		Context: ctx,
	}
}

// NewGetProjectProjectIDRunnerTagsParamsWithHTTPClient creates a new GetProjectProjectIDRunnerTagsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectProjectIDRunnerTagsParamsWithHTTPClient(client *http.Client) *GetProjectProjectIDRunnerTagsParams {
	return &GetProjectProjectIDRunnerTagsParams{
		HTTPClient: client,
	}
}

/*
GetProjectProjectIDRunnerTagsParams contains all the parameters to send to the API endpoint

	for the get project project ID runner tags operation.

	Typically these are written to a http.Request.
*/
type GetProjectProjectIDRunnerTagsParams struct {

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get project project ID runner tags params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectProjectIDRunnerTagsParams) WithDefaults() *GetProjectProjectIDRunnerTagsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get project project ID runner tags params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectProjectIDRunnerTagsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get project project ID runner tags params
func (o *GetProjectProjectIDRunnerTagsParams) WithTimeout(timeout time.Duration) *GetProjectProjectIDRunnerTagsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project project ID runner tags params
func (o *GetProjectProjectIDRunnerTagsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get project project ID runner tags params
func (o *GetProjectProjectIDRunnerTagsParams) WithContext(ctx context.Context) *GetProjectProjectIDRunnerTagsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project project ID runner tags params
func (o *GetProjectProjectIDRunnerTagsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get project project ID runner tags params
func (o *GetProjectProjectIDRunnerTagsParams) WithHTTPClient(client *http.Client) *GetProjectProjectIDRunnerTagsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project project ID runner tags params
func (o *GetProjectProjectIDRunnerTagsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectID adds the projectID to the get project project ID runner tags params
func (o *GetProjectProjectIDRunnerTagsParams) WithProjectID(projectID int64) *GetProjectProjectIDRunnerTagsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get project project ID runner tags params
func (o *GetProjectProjectIDRunnerTagsParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *GetProjectProjectIDRunnerTagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param project_id
	if err := r.SetPathParam("project_id", swag.FormatInt64(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
