// Code generated by go-swagger; DO NOT EDIT.

package runner

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"terraform-provider-semaphoreui/semaphoreui/models"
)

// GetProjectProjectIDRunnersRunnerIDReader is a Reader for the GetProjectProjectIDRunnersRunnerID structure.
type GetProjectProjectIDRunnersRunnerIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectProjectIDRunnersRunnerIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectProjectIDRunnersRunnerIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetProjectProjectIDRunnersRunnerIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /project/{project_id}/runners/{runner_id}] GetProjectProjectIDRunnersRunnerID", response, response.Code())
	}
}

// NewGetProjectProjectIDRunnersRunnerIDOK creates a GetProjectProjectIDRunnersRunnerIDOK with default headers values
func NewGetProjectProjectIDRunnersRunnerIDOK() *GetProjectProjectIDRunnersRunnerIDOK {
	return &GetProjectProjectIDRunnersRunnerIDOK{}
}

/*
GetProjectProjectIDRunnersRunnerIDOK describes a response with status code 200, with default header values.

Runner
*/
type GetProjectProjectIDRunnersRunnerIDOK struct {
	Payload *models.Runner
}

// IsSuccess returns true when this get project project Id runners runner Id o k response has a 2xx status code
func (o *GetProjectProjectIDRunnersRunnerIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get project project Id runners runner Id o k response has a 3xx status code
func (o *GetProjectProjectIDRunnersRunnerIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project project Id runners runner Id o k response has a 4xx status code
func (o *GetProjectProjectIDRunnersRunnerIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get project project Id runners runner Id o k response has a 5xx status code
func (o *GetProjectProjectIDRunnersRunnerIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get project project Id runners runner Id o k response a status code equal to that given
func (o *GetProjectProjectIDRunnersRunnerIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get project project Id runners runner Id o k response
func (o *GetProjectProjectIDRunnersRunnerIDOK) Code() int {
	return 200
}

func (o *GetProjectProjectIDRunnersRunnerIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{project_id}/runners/{runner_id}][%d] getProjectProjectIdRunnersRunnerIdOK %s", 200, payload)
}

func (o *GetProjectProjectIDRunnersRunnerIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{project_id}/runners/{runner_id}][%d] getProjectProjectIdRunnersRunnerIdOK %s", 200, payload)
}

func (o *GetProjectProjectIDRunnersRunnerIDOK) GetPayload() *models.Runner {
	return o.Payload
}

func (o *GetProjectProjectIDRunnersRunnerIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Runner)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetProjectProjectIDRunnersRunnerIDNotFound creates a GetProjectProjectIDRunnersRunnerIDNotFound with default headers values
func NewGetProjectProjectIDRunnersRunnerIDNotFound() *GetProjectProjectIDRunnersRunnerIDNotFound {
	return &GetProjectProjectIDRunnersRunnerIDNotFound{}
}

/*
GetProjectProjectIDRunnersRunnerIDNotFound describes a response with status code 404, with default header values.

Runner not found
*/
type GetProjectProjectIDRunnersRunnerIDNotFound struct {
}

// IsSuccess returns true when this get project project Id runners runner Id not found response has a 2xx status code
func (o *GetProjectProjectIDRunnersRunnerIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get project project Id runners runner Id not found response has a 3xx status code
func (o *GetProjectProjectIDRunnersRunnerIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project project Id runners runner Id not found response has a 4xx status code
func (o *GetProjectProjectIDRunnersRunnerIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get project project Id runners runner Id not found response has a 5xx status code
func (o *GetProjectProjectIDRunnersRunnerIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get project project Id runners runner Id not found response a status code equal to that given
func (o *GetProjectProjectIDRunnersRunnerIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get project project Id runners runner Id not found response
func (o *GetProjectProjectIDRunnersRunnerIDNotFound) Code() int {
	return 404
}

func (o *GetProjectProjectIDRunnersRunnerIDNotFound) Error() string {
	return fmt.Sprintf("[GET /project/{project_id}/runners/{runner_id}][%d] getProjectProjectIdRunnersRunnerIdNotFound", 404)
}

func (o *GetProjectProjectIDRunnersRunnerIDNotFound) String() string {
	return fmt.Sprintf("[GET /project/{project_id}/runners/{runner_id}][%d] getProjectProjectIdRunnersRunnerIdNotFound", 404)
}

func (o *GetProjectProjectIDRunnersRunnerIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
