// Code generated by go-swagger; DO NOT EDIT.

package runner

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostProjectProjectIDRunnersRunnerIDActiveReader is a Reader for the PostProjectProjectIDRunnersRunnerIDActive structure.
type PostProjectProjectIDRunnersRunnerIDActiveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostProjectProjectIDRunnersRunnerIDActiveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewPostProjectProjectIDRunnersRunnerIDActiveNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostProjectProjectIDRunnersRunnerIDActiveBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /project/{project_id}/runners/{runner_id}/active] PostProjectProjectIDRunnersRunnerIDActive", response, response.Code())
	}
}

// NewPostProjectProjectIDRunnersRunnerIDActiveNoContent creates a PostProjectProjectIDRunnersRunnerIDActiveNoContent with default headers values
func NewPostProjectProjectIDRunnersRunnerIDActiveNoContent() *PostProjectProjectIDRunnersRunnerIDActiveNoContent {
	return &PostProjectProjectIDRunnersRunnerIDActiveNoContent{}
}

/*
PostProjectProjectIDRunnersRunnerIDActiveNoContent describes a response with status code 204, with default header values.

Runner active state updated
*/
type PostProjectProjectIDRunnersRunnerIDActiveNoContent struct {
}

// IsSuccess returns true when this post project project Id runners runner Id active no content response has a 2xx status code
func (o *PostProjectProjectIDRunnersRunnerIDActiveNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post project project Id runners runner Id active no content response has a 3xx status code
func (o *PostProjectProjectIDRunnersRunnerIDActiveNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post project project Id runners runner Id active no content response has a 4xx status code
func (o *PostProjectProjectIDRunnersRunnerIDActiveNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post project project Id runners runner Id active no content response has a 5xx status code
func (o *PostProjectProjectIDRunnersRunnerIDActiveNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post project project Id runners runner Id active no content response a status code equal to that given
func (o *PostProjectProjectIDRunnersRunnerIDActiveNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the post project project Id runners runner Id active no content response
func (o *PostProjectProjectIDRunnersRunnerIDActiveNoContent) Code() int {
	return 204
}

func (o *PostProjectProjectIDRunnersRunnerIDActiveNoContent) Error() string {
	return fmt.Sprintf("[POST /project/{project_id}/runners/{runner_id}/active][%d] postProjectProjectIdRunnersRunnerIdActiveNoContent", 204)
}

func (o *PostProjectProjectIDRunnersRunnerIDActiveNoContent) String() string {
	return fmt.Sprintf("[POST /project/{project_id}/runners/{runner_id}/active][%d] postProjectProjectIdRunnersRunnerIdActiveNoContent", 204)
}

func (o *PostProjectProjectIDRunnersRunnerIDActiveNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostProjectProjectIDRunnersRunnerIDActiveBadRequest creates a PostProjectProjectIDRunnersRunnerIDActiveBadRequest with default headers values
func NewPostProjectProjectIDRunnersRunnerIDActiveBadRequest() *PostProjectProjectIDRunnersRunnerIDActiveBadRequest {
	return &PostProjectProjectIDRunnersRunnerIDActiveBadRequest{}
}

/*
PostProjectProjectIDRunnersRunnerIDActiveBadRequest describes a response with status code 400, with default header values.

Invalid request body
*/
type PostProjectProjectIDRunnersRunnerIDActiveBadRequest struct {
}

// IsSuccess returns true when this post project project Id runners runner Id active bad request response has a 2xx status code
func (o *PostProjectProjectIDRunnersRunnerIDActiveBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post project project Id runners runner Id active bad request response has a 3xx status code
func (o *PostProjectProjectIDRunnersRunnerIDActiveBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post project project Id runners runner Id active bad request response has a 4xx status code
func (o *PostProjectProjectIDRunnersRunnerIDActiveBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post project project Id runners runner Id active bad request response has a 5xx status code
func (o *PostProjectProjectIDRunnersRunnerIDActiveBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post project project Id runners runner Id active bad request response a status code equal to that given
func (o *PostProjectProjectIDRunnersRunnerIDActiveBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post project project Id runners runner Id active bad request response
func (o *PostProjectProjectIDRunnersRunnerIDActiveBadRequest) Code() int {
	return 400
}

func (o *PostProjectProjectIDRunnersRunnerIDActiveBadRequest) Error() string {
	return fmt.Sprintf("[POST /project/{project_id}/runners/{runner_id}/active][%d] postProjectProjectIdRunnersRunnerIdActiveBadRequest", 400)
}

func (o *PostProjectProjectIDRunnersRunnerIDActiveBadRequest) String() string {
	return fmt.Sprintf("[POST /project/{project_id}/runners/{runner_id}/active][%d] postProjectProjectIdRunnersRunnerIdActiveBadRequest", 400)
}

func (o *PostProjectProjectIDRunnersRunnerIDActiveBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
