// Code generated by go-swagger; DO NOT EDIT.

package runner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"terraform-provider-semaphoreui/semaphoreui/models"
)

// NewPostRunnersParams creates a new PostRunnersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostRunnersParams() *PostRunnersParams {
	return &PostRunnersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostRunnersParamsWithTimeout creates a new PostRunnersParams object
// with the ability to set a timeout on a request.
func NewPostRunnersParamsWithTimeout(timeout time.Duration) *PostRunnersParams {
	return &PostRunnersParams{
		timeout: timeout,
	}
}

// NewPostRunnersParamsWithContext creates a new PostRunnersParams object
// with the ability to set a context for a request.
func NewPostRunnersParamsWithContext(ctx context.Context) *PostRunnersParams {
	return &PostRunnersParams{
		Context: ctx,
	}
}

// NewPostRunnersParamsWithHTTPClient creates a new PostRunnersParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostRunnersParamsWithHTTPClient(client *http.Client) *PostRunnersParams {
	return &PostRunnersParams{
		HTTPClient: client,
	}
}

/*
PostRunnersParams contains all the parameters to send to the API endpoint

	for the post runners operation.

	Typically these are written to a http.Request.
*/
type PostRunnersParams struct {

	// Runner.
	Runner *models.RunnerRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post runners params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRunnersParams) WithDefaults() *PostRunnersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post runners params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRunnersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post runners params
func (o *PostRunnersParams) WithTimeout(timeout time.Duration) *PostRunnersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post runners params
func (o *PostRunnersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post runners params
func (o *PostRunnersParams) WithContext(ctx context.Context) *PostRunnersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post runners params
func (o *PostRunnersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post runners params
func (o *PostRunnersParams) WithHTTPClient(client *http.Client) *PostRunnersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post runners params
func (o *PostRunnersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRunner adds the runner to the post runners params
func (o *PostRunnersParams) WithRunner(runner *models.RunnerRequest) *PostRunnersParams {
	o.SetRunner(runner)
	return o
}

// SetRunner adds the runner to the post runners params
func (o *PostRunnersParams) SetRunner(runner *models.RunnerRequest) {
	o.Runner = runner
}

// WriteToRequest writes these params to a swagger request
func (o *PostRunnersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Runner != nil {
		if err := r.SetBodyParam(o.Runner); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
