// Code generated by go-swagger; DO NOT EDIT.

package runner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"terraform-provider-semaphoreui/semaphoreui/models"
)

// NewPostProjectProjectIDRunnersParams creates a new PostProjectProjectIDRunnersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostProjectProjectIDRunnersParams() *PostProjectProjectIDRunnersParams {
	return &PostProjectProjectIDRunnersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostProjectProjectIDRunnersParamsWithTimeout creates a new PostProjectProjectIDRunnersParams object
// with the ability to set a timeout on a request.
func NewPostProjectProjectIDRunnersParamsWithTimeout(timeout time.Duration) *PostProjectProjectIDRunnersParams {
	return &PostProjectProjectIDRunnersParams{
		timeout: timeout,
	}
}

// NewPostProjectProjectIDRunnersParamsWithContext creates a new PostProjectProjectIDRunnersParams object
// with the ability to set a context for a request.
func NewPostProjectProjectIDRunnersParamsWithContext(ctx context.Context) *PostProjectProjectIDRunnersParams {
	return &PostProjectProjectIDRunnersParams{
		Context: ctx,
	}
}

// NewPostProjectProjectIDRunnersParamsWithHTTPClient creates a new PostProjectProjectIDRunnersParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostProjectProjectIDRunnersParamsWithHTTPClient(client *http.Client) *PostProjectProjectIDRunnersParams {
	return &PostProjectProjectIDRunnersParams{
		HTTPClient: client,
	}
}

/*
PostProjectProjectIDRunnersParams contains all the parameters to send to the API endpoint

	for the post project project ID runners operation.

	Typically these are written to a http.Request.
*/
type PostProjectProjectIDRunnersParams struct {

	// Runner.
	Runner *models.RunnerRequest

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post project project ID runners params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProjectProjectIDRunnersParams) WithDefaults() *PostProjectProjectIDRunnersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post project project ID runners params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProjectProjectIDRunnersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post project project ID runners params
func (o *PostProjectProjectIDRunnersParams) WithTimeout(timeout time.Duration) *PostProjectProjectIDRunnersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post project project ID runners params
func (o *PostProjectProjectIDRunnersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post project project ID runners params
func (o *PostProjectProjectIDRunnersParams) WithContext(ctx context.Context) *PostProjectProjectIDRunnersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post project project ID runners params
func (o *PostProjectProjectIDRunnersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post project project ID runners params
func (o *PostProjectProjectIDRunnersParams) WithHTTPClient(client *http.Client) *PostProjectProjectIDRunnersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post project project ID runners params
func (o *PostProjectProjectIDRunnersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRunner adds the runner to the post project project ID runners params
func (o *PostProjectProjectIDRunnersParams) WithRunner(runner *models.RunnerRequest) *PostProjectProjectIDRunnersParams {
	o.SetRunner(runner)
	return o
}

// SetRunner adds the runner to the post project project ID runners params
func (o *PostProjectProjectIDRunnersParams) SetRunner(runner *models.RunnerRequest) {
	o.Runner = runner
}

// WithProjectID adds the projectID to the post project project ID runners params
func (o *PostProjectProjectIDRunnersParams) WithProjectID(projectID int64) *PostProjectProjectIDRunnersParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the post project project ID runners params
func (o *PostProjectProjectIDRunnersParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *PostProjectProjectIDRunnersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Runner != nil {
		if err := r.SetBodyParam(o.Runner); err != nil {
			return err
		}
	}

	// path param project_id
	if err := r.SetPathParam("project_id", swag.FormatInt64(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
