// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"terraform-provider-semaphoreui/semaphoreui/models"
)

// NewPostUserOptionsParams creates a new PostUserOptionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostUserOptionsParams() *PostUserOptionsParams {
	return &PostUserOptionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostUserOptionsParamsWithTimeout creates a new PostUserOptionsParams object
// with the ability to set a timeout on a request.
func NewPostUserOptionsParamsWithTimeout(timeout time.Duration) *PostUserOptionsParams {
	return &PostUserOptionsParams{
		timeout: timeout,
	}
}

// NewPostUserOptionsParamsWithContext creates a new PostUserOptionsParams object
// with the ability to set a context for a request.
func NewPostUserOptionsParamsWithContext(ctx context.Context) *PostUserOptionsParams {
	return &PostUserOptionsParams{
		Context: ctx,
	}
}

// NewPostUserOptionsParamsWithHTTPClient creates a new PostUserOptionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostUserOptionsParamsWithHTTPClient(client *http.Client) *PostUserOptionsParams {
	return &PostUserOptionsParams{
		HTTPClient: client,
	}
}

/*
PostUserOptionsParams contains all the parameters to send to the API endpoint

	for the post user options operation.

	Typically these are written to a http.Request.
*/
type PostUserOptionsParams struct {

	// Body.
	Body *models.Option

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post user options params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostUserOptionsParams) WithDefaults() *PostUserOptionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post user options params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostUserOptionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post user options params
func (o *PostUserOptionsParams) WithTimeout(timeout time.Duration) *PostUserOptionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post user options params
func (o *PostUserOptionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post user options params
func (o *PostUserOptionsParams) WithContext(ctx context.Context) *PostUserOptionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post user options params
func (o *PostUserOptionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post user options params
func (o *PostUserOptionsParams) WithHTTPClient(client *http.Client) *PostUserOptionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post user options params
func (o *PostUserOptionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post user options params
func (o *PostUserOptionsParams) WithBody(body *models.Option) *PostUserOptionsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post user options params
func (o *PostUserOptionsParams) SetBody(body *models.Option) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostUserOptionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
