// Code generated by go-swagger; DO NOT EDIT.

package inventory

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteProjectProjectIDInventoryInventoryIDReader is a Reader for the DeleteProjectProjectIDInventoryInventoryID structure.
type DeleteProjectProjectIDInventoryInventoryIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProjectProjectIDInventoryInventoryIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteProjectProjectIDInventoryInventoryIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /project/{project_id}/inventory/{inventory_id}] DeleteProjectProjectIDInventoryInventoryID", response, response.Code())
	}
}

// NewDeleteProjectProjectIDInventoryInventoryIDNoContent creates a DeleteProjectProjectIDInventoryInventoryIDNoContent with default headers values
func NewDeleteProjectProjectIDInventoryInventoryIDNoContent() *DeleteProjectProjectIDInventoryInventoryIDNoContent {
	return &DeleteProjectProjectIDInventoryInventoryIDNoContent{}
}

/*
DeleteProjectProjectIDInventoryInventoryIDNoContent describes a response with status code 204, with default header values.

inventory removed
*/
type DeleteProjectProjectIDInventoryInventoryIDNoContent struct {
}

// IsSuccess returns true when this delete project project Id inventory inventory Id no content response has a 2xx status code
func (o *DeleteProjectProjectIDInventoryInventoryIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete project project Id inventory inventory Id no content response has a 3xx status code
func (o *DeleteProjectProjectIDInventoryInventoryIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete project project Id inventory inventory Id no content response has a 4xx status code
func (o *DeleteProjectProjectIDInventoryInventoryIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete project project Id inventory inventory Id no content response has a 5xx status code
func (o *DeleteProjectProjectIDInventoryInventoryIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete project project Id inventory inventory Id no content response a status code equal to that given
func (o *DeleteProjectProjectIDInventoryInventoryIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete project project Id inventory inventory Id no content response
func (o *DeleteProjectProjectIDInventoryInventoryIDNoContent) Code() int {
	return 204
}

func (o *DeleteProjectProjectIDInventoryInventoryIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /project/{project_id}/inventory/{inventory_id}][%d] deleteProjectProjectIdInventoryInventoryIdNoContent", 204)
}

func (o *DeleteProjectProjectIDInventoryInventoryIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /project/{project_id}/inventory/{inventory_id}][%d] deleteProjectProjectIdInventoryInventoryIdNoContent", 204)
}

func (o *DeleteProjectProjectIDInventoryInventoryIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
