// Code generated by go-swagger; DO NOT EDIT.

package inventory

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new inventory API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new inventory API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new inventory API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for inventory API.
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// This client is generated with a few options you might find useful for your swagger spec.
//
// Feel free to add you own set of options.

// WithAccept allows the client to force the Accept header
// to negotiate a specific Producer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithAccept(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ProducesMediaTypes = []string{mime}
	}
}

// WithAcceptApplicationJSON sets the Accept header to "application/json".
func WithAcceptApplicationJSON(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/json"}
}

// WithAcceptTextPlainCharsetUTF8 sets the Accept header to "text/plain; charset=utf-8".
func WithAcceptTextPlainCharsetUTF8(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"text/plain; charset=utf-8"}
}

// ClientService is the interface for Client methods.
type ClientService interface {

	// DeleteProjectProjectIDInventoryInventoryID removes inventory.
	DeleteProjectProjectIDInventoryInventoryID(params *DeleteProjectProjectIDInventoryInventoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectProjectIDInventoryInventoryIDNoContent, error)

	// DeleteProjectProjectIDInventoryInventoryIDContext removes inventory.
	DeleteProjectProjectIDInventoryInventoryIDContext(ctx context.Context, params *DeleteProjectProjectIDInventoryInventoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectProjectIDInventoryInventoryIDNoContent, error)

	// GetProjectProjectIDInventory get inventory.
	GetProjectProjectIDInventory(params *GetProjectProjectIDInventoryParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDInventoryOK, error)

	// GetProjectProjectIDInventoryContext get inventory.
	GetProjectProjectIDInventoryContext(ctx context.Context, params *GetProjectProjectIDInventoryParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDInventoryOK, error)

	// GetProjectProjectIDInventoryInventoryID get inventory.
	GetProjectProjectIDInventoryInventoryID(params *GetProjectProjectIDInventoryInventoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDInventoryInventoryIDOK, error)

	// GetProjectProjectIDInventoryInventoryIDContext get inventory.
	GetProjectProjectIDInventoryInventoryIDContext(ctx context.Context, params *GetProjectProjectIDInventoryInventoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDInventoryInventoryIDOK, error)

	// PostProjectProjectIDInventory create inventory.
	PostProjectProjectIDInventory(params *PostProjectProjectIDInventoryParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProjectProjectIDInventoryCreated, error)

	// PostProjectProjectIDInventoryContext create inventory.
	PostProjectProjectIDInventoryContext(ctx context.Context, params *PostProjectProjectIDInventoryParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProjectProjectIDInventoryCreated, error)

	// PutProjectProjectIDInventoryInventoryID updates inventory.
	PutProjectProjectIDInventoryInventoryID(params *PutProjectProjectIDInventoryInventoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProjectProjectIDInventoryInventoryIDNoContent, error)

	// PutProjectProjectIDInventoryInventoryIDContext updates inventory.
	PutProjectProjectIDInventoryInventoryIDContext(ctx context.Context, params *PutProjectProjectIDInventoryInventoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProjectProjectIDInventoryInventoryIDNoContent, error)

	SetTransport(transport runtime.ContextualTransport)
}

/*
DeleteProjectProjectIDInventoryInventoryIDremoves inventory.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.DeleteProjectProjectIDInventoryInventoryIDContext] instead.
*/
func (a *Client) DeleteProjectProjectIDInventoryInventoryID(params *DeleteProjectProjectIDInventoryInventoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectProjectIDInventoryInventoryIDNoContent, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.DeleteProjectProjectIDInventoryInventoryIDContext(ctx, params, authInfo, opts...)
}

/*
DeleteProjectProjectIDInventoryInventoryIDContextremoves inventory.

Do not use the deprecated [DeleteProjectProjectIDInventoryInventoryIDParams.Context] with this method: it would be ignored.
*/
func (a *Client) DeleteProjectProjectIDInventoryInventoryIDContext(ctx context.Context, params *DeleteProjectProjectIDInventoryInventoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectProjectIDInventoryInventoryIDNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteProjectProjectIDInventoryInventoryIDParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "DeleteProjectProjectIDInventoryInventoryID",
		Method:             "DELETE",
		PathPattern:        "/project/{project_id}/inventory/{inventory_id}",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteProjectProjectIDInventoryInventoryIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteProjectProjectIDInventoryInventoryIDNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteProjectProjectIDInventoryInventoryID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetProjectProjectIDInventorygets inventory.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetProjectProjectIDInventoryContext] instead.
*/
func (a *Client) GetProjectProjectIDInventory(params *GetProjectProjectIDInventoryParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDInventoryOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetProjectProjectIDInventoryContext(ctx, params, authInfo, opts...)
}

/*
GetProjectProjectIDInventoryContextgets inventory.

Do not use the deprecated [GetProjectProjectIDInventoryParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetProjectProjectIDInventoryContext(ctx context.Context, params *GetProjectProjectIDInventoryParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDInventoryOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProjectProjectIDInventoryParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetProjectProjectIDInventory",
		Method:             "GET",
		PathPattern:        "/project/{project_id}/inventory",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetProjectProjectIDInventoryReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProjectProjectIDInventoryOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetProjectProjectIDInventory: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetProjectProjectIDInventoryInventoryIDgets inventory.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetProjectProjectIDInventoryInventoryIDContext] instead.
*/
func (a *Client) GetProjectProjectIDInventoryInventoryID(params *GetProjectProjectIDInventoryInventoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDInventoryInventoryIDOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetProjectProjectIDInventoryInventoryIDContext(ctx, params, authInfo, opts...)
}

/*
GetProjectProjectIDInventoryInventoryIDContextgets inventory.

Do not use the deprecated [GetProjectProjectIDInventoryInventoryIDParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetProjectProjectIDInventoryInventoryIDContext(ctx context.Context, params *GetProjectProjectIDInventoryInventoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDInventoryInventoryIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProjectProjectIDInventoryInventoryIDParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetProjectProjectIDInventoryInventoryID",
		Method:             "GET",
		PathPattern:        "/project/{project_id}/inventory/{inventory_id}",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetProjectProjectIDInventoryInventoryIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProjectProjectIDInventoryInventoryIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetProjectProjectIDInventoryInventoryID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostProjectProjectIDInventorycreates inventory.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostProjectProjectIDInventoryContext] instead.
*/
func (a *Client) PostProjectProjectIDInventory(params *PostProjectProjectIDInventoryParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProjectProjectIDInventoryCreated, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostProjectProjectIDInventoryContext(ctx, params, authInfo, opts...)
}

/*
PostProjectProjectIDInventoryContextcreates inventory.

Do not use the deprecated [PostProjectProjectIDInventoryParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostProjectProjectIDInventoryContext(ctx context.Context, params *PostProjectProjectIDInventoryParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProjectProjectIDInventoryCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostProjectProjectIDInventoryParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostProjectProjectIDInventory",
		Method:             "POST",
		PathPattern:        "/project/{project_id}/inventory",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PostProjectProjectIDInventoryReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostProjectProjectIDInventoryCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostProjectProjectIDInventory: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutProjectProjectIDInventoryInventoryIDupdates inventory.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PutProjectProjectIDInventoryInventoryIDContext] instead.
*/
func (a *Client) PutProjectProjectIDInventoryInventoryID(params *PutProjectProjectIDInventoryInventoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProjectProjectIDInventoryInventoryIDNoContent, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PutProjectProjectIDInventoryInventoryIDContext(ctx, params, authInfo, opts...)
}

/*
PutProjectProjectIDInventoryInventoryIDContextupdates inventory.

Do not use the deprecated [PutProjectProjectIDInventoryInventoryIDParams.Context] with this method: it would be ignored.
*/
func (a *Client) PutProjectProjectIDInventoryInventoryIDContext(ctx context.Context, params *PutProjectProjectIDInventoryInventoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProjectProjectIDInventoryInventoryIDNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutProjectProjectIDInventoryInventoryIDParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PutProjectProjectIDInventoryInventoryID",
		Method:             "PUT",
		PathPattern:        "/project/{project_id}/inventory/{inventory_id}",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PutProjectProjectIDInventoryInventoryIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutProjectProjectIDInventoryInventoryIDNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutProjectProjectIDInventoryInventoryID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [InventoryParams].
	ctx context.Context
}
