// Code generated by go-swagger; DO NOT EDIT.

package inventory

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new inventory API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new inventory API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new inventory API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for inventory API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// This client is generated with a few options you might find useful for your swagger spec.
//
// Feel free to add you own set of options.

// WithAccept allows the client to force the Accept header
// to negotiate a specific Producer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithAccept(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ProducesMediaTypes = []string{mime}
	}
}

// WithAcceptApplicationJSON sets the Accept header to "application/json".
func WithAcceptApplicationJSON(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/json"}
}

// WithAcceptTextPlainCharsetUTF8 sets the Accept header to "text/plain; charset=utf-8".
func WithAcceptTextPlainCharsetUTF8(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"text/plain; charset=utf-8"}
}

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteProjectProjectIDInventoryInventoryID(params *DeleteProjectProjectIDInventoryInventoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectProjectIDInventoryInventoryIDNoContent, error)

	GetProjectProjectIDInventory(params *GetProjectProjectIDInventoryParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDInventoryOK, error)

	GetProjectProjectIDInventoryInventoryID(params *GetProjectProjectIDInventoryInventoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDInventoryInventoryIDOK, error)

	PostProjectProjectIDInventory(params *PostProjectProjectIDInventoryParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProjectProjectIDInventoryCreated, error)

	PutProjectProjectIDInventoryInventoryID(params *PutProjectProjectIDInventoryInventoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProjectProjectIDInventoryInventoryIDNoContent, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteProjectProjectIDInventoryInventoryID removes inventory
*/
func (a *Client) DeleteProjectProjectIDInventoryInventoryID(params *DeleteProjectProjectIDInventoryInventoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectProjectIDInventoryInventoryIDNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteProjectProjectIDInventoryInventoryIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteProjectProjectIDInventoryInventoryID",
		Method:             "DELETE",
		PathPattern:        "/project/{project_id}/inventory/{inventory_id}",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteProjectProjectIDInventoryInventoryIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteProjectProjectIDInventoryInventoryIDNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteProjectProjectIDInventoryInventoryID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetProjectProjectIDInventory gets inventory
*/
func (a *Client) GetProjectProjectIDInventory(params *GetProjectProjectIDInventoryParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDInventoryOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProjectProjectIDInventoryParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProjectProjectIDInventory",
		Method:             "GET",
		PathPattern:        "/project/{project_id}/inventory",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetProjectProjectIDInventoryReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProjectProjectIDInventoryOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetProjectProjectIDInventory: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetProjectProjectIDInventoryInventoryID gets inventory
*/
func (a *Client) GetProjectProjectIDInventoryInventoryID(params *GetProjectProjectIDInventoryInventoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDInventoryInventoryIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProjectProjectIDInventoryInventoryIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProjectProjectIDInventoryInventoryID",
		Method:             "GET",
		PathPattern:        "/project/{project_id}/inventory/{inventory_id}",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetProjectProjectIDInventoryInventoryIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProjectProjectIDInventoryInventoryIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetProjectProjectIDInventoryInventoryID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostProjectProjectIDInventory creates inventory
*/
func (a *Client) PostProjectProjectIDInventory(params *PostProjectProjectIDInventoryParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProjectProjectIDInventoryCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostProjectProjectIDInventoryParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostProjectProjectIDInventory",
		Method:             "POST",
		PathPattern:        "/project/{project_id}/inventory",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PostProjectProjectIDInventoryReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostProjectProjectIDInventoryCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostProjectProjectIDInventory: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutProjectProjectIDInventoryInventoryID updates inventory
*/
func (a *Client) PutProjectProjectIDInventoryInventoryID(params *PutProjectProjectIDInventoryInventoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProjectProjectIDInventoryInventoryIDNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutProjectProjectIDInventoryInventoryIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutProjectProjectIDInventoryInventoryID",
		Method:             "PUT",
		PathPattern:        "/project/{project_id}/inventory/{inventory_id}",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PutProjectProjectIDInventoryInventoryIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutProjectProjectIDInventoryInventoryIDNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutProjectProjectIDInventoryInventoryID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
