// Code generated by go-swagger; DO NOT EDIT.

package inventory

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"terraform-provider-semaphoreui/semaphoreui/models"
)

// NewPutProjectProjectIDInventoryInventoryIDParams creates a new PutProjectProjectIDInventoryInventoryIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutProjectProjectIDInventoryInventoryIDParams() *PutProjectProjectIDInventoryInventoryIDParams {
	return &PutProjectProjectIDInventoryInventoryIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutProjectProjectIDInventoryInventoryIDParamsWithTimeout creates a new PutProjectProjectIDInventoryInventoryIDParams object
// with the ability to set a timeout on a request.
func NewPutProjectProjectIDInventoryInventoryIDParamsWithTimeout(timeout time.Duration) *PutProjectProjectIDInventoryInventoryIDParams {
	return &PutProjectProjectIDInventoryInventoryIDParams{
		timeout: timeout,
	}
}

// NewPutProjectProjectIDInventoryInventoryIDParamsWithContext creates a new PutProjectProjectIDInventoryInventoryIDParams object
// with the ability to set a context for a request.
func NewPutProjectProjectIDInventoryInventoryIDParamsWithContext(ctx context.Context) *PutProjectProjectIDInventoryInventoryIDParams {
	return &PutProjectProjectIDInventoryInventoryIDParams{
		Context: ctx,
	}
}

// NewPutProjectProjectIDInventoryInventoryIDParamsWithHTTPClient creates a new PutProjectProjectIDInventoryInventoryIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutProjectProjectIDInventoryInventoryIDParamsWithHTTPClient(client *http.Client) *PutProjectProjectIDInventoryInventoryIDParams {
	return &PutProjectProjectIDInventoryInventoryIDParams{
		HTTPClient: client,
	}
}

/*
PutProjectProjectIDInventoryInventoryIDParams contains all the parameters to send to the API endpoint

	for the put project project ID inventory inventory ID operation.

	Typically these are written to a http.Request.
*/
type PutProjectProjectIDInventoryInventoryIDParams struct {

	// Inventory.
	Inventory *models.InventoryRequest

	/* InventoryID.

	   inventory ID
	*/
	InventoryID int64

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put project project ID inventory inventory ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProjectProjectIDInventoryInventoryIDParams) WithDefaults() *PutProjectProjectIDInventoryInventoryIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put project project ID inventory inventory ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProjectProjectIDInventoryInventoryIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put project project ID inventory inventory ID params
func (o *PutProjectProjectIDInventoryInventoryIDParams) WithTimeout(timeout time.Duration) *PutProjectProjectIDInventoryInventoryIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put project project ID inventory inventory ID params
func (o *PutProjectProjectIDInventoryInventoryIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put project project ID inventory inventory ID params
func (o *PutProjectProjectIDInventoryInventoryIDParams) WithContext(ctx context.Context) *PutProjectProjectIDInventoryInventoryIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put project project ID inventory inventory ID params
func (o *PutProjectProjectIDInventoryInventoryIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put project project ID inventory inventory ID params
func (o *PutProjectProjectIDInventoryInventoryIDParams) WithHTTPClient(client *http.Client) *PutProjectProjectIDInventoryInventoryIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put project project ID inventory inventory ID params
func (o *PutProjectProjectIDInventoryInventoryIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInventory adds the inventory to the put project project ID inventory inventory ID params
func (o *PutProjectProjectIDInventoryInventoryIDParams) WithInventory(inventory *models.InventoryRequest) *PutProjectProjectIDInventoryInventoryIDParams {
	o.SetInventory(inventory)
	return o
}

// SetInventory adds the inventory to the put project project ID inventory inventory ID params
func (o *PutProjectProjectIDInventoryInventoryIDParams) SetInventory(inventory *models.InventoryRequest) {
	o.Inventory = inventory
}

// WithInventoryID adds the inventoryID to the put project project ID inventory inventory ID params
func (o *PutProjectProjectIDInventoryInventoryIDParams) WithInventoryID(inventoryID int64) *PutProjectProjectIDInventoryInventoryIDParams {
	o.SetInventoryID(inventoryID)
	return o
}

// SetInventoryID adds the inventoryId to the put project project ID inventory inventory ID params
func (o *PutProjectProjectIDInventoryInventoryIDParams) SetInventoryID(inventoryID int64) {
	o.InventoryID = inventoryID
}

// WithProjectID adds the projectID to the put project project ID inventory inventory ID params
func (o *PutProjectProjectIDInventoryInventoryIDParams) WithProjectID(projectID int64) *PutProjectProjectIDInventoryInventoryIDParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the put project project ID inventory inventory ID params
func (o *PutProjectProjectIDInventoryInventoryIDParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *PutProjectProjectIDInventoryInventoryIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Inventory != nil {
		if err := r.SetBodyParam(o.Inventory); err != nil {
			return err
		}
	}

	// path param inventory_id
	if err := r.SetPathParam("inventory_id", swag.FormatInt64(o.InventoryID)); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", swag.FormatInt64(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
