// Code generated by go-swagger; DO NOT EDIT.

package repository

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"terraform-provider-semaphoreui/semaphoreui/models"
)

// NewPostProjectProjectIDRepositoriesParams creates a new PostProjectProjectIDRepositoriesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostProjectProjectIDRepositoriesParams() *PostProjectProjectIDRepositoriesParams {
	return &PostProjectProjectIDRepositoriesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostProjectProjectIDRepositoriesParamsWithTimeout creates a new PostProjectProjectIDRepositoriesParams object
// with the ability to set a timeout on a request.
func NewPostProjectProjectIDRepositoriesParamsWithTimeout(timeout time.Duration) *PostProjectProjectIDRepositoriesParams {
	return &PostProjectProjectIDRepositoriesParams{
		timeout: timeout,
	}
}

// NewPostProjectProjectIDRepositoriesParamsWithContext creates a new PostProjectProjectIDRepositoriesParams object
// with the ability to set a context for a request.
func NewPostProjectProjectIDRepositoriesParamsWithContext(ctx context.Context) *PostProjectProjectIDRepositoriesParams {
	return &PostProjectProjectIDRepositoriesParams{
		Context: ctx,
	}
}

// NewPostProjectProjectIDRepositoriesParamsWithHTTPClient creates a new PostProjectProjectIDRepositoriesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostProjectProjectIDRepositoriesParamsWithHTTPClient(client *http.Client) *PostProjectProjectIDRepositoriesParams {
	return &PostProjectProjectIDRepositoriesParams{
		HTTPClient: client,
	}
}

/*
PostProjectProjectIDRepositoriesParams contains all the parameters to send to the API endpoint

	for the post project project ID repositories operation.

	Typically these are written to a http.Request.
*/
type PostProjectProjectIDRepositoriesParams struct {

	// Repository.
	Repository *models.RepositoryRequest

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post project project ID repositories params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProjectProjectIDRepositoriesParams) WithDefaults() *PostProjectProjectIDRepositoriesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post project project ID repositories params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProjectProjectIDRepositoriesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post project project ID repositories params
func (o *PostProjectProjectIDRepositoriesParams) WithTimeout(timeout time.Duration) *PostProjectProjectIDRepositoriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post project project ID repositories params
func (o *PostProjectProjectIDRepositoriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post project project ID repositories params
func (o *PostProjectProjectIDRepositoriesParams) WithContext(ctx context.Context) *PostProjectProjectIDRepositoriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post project project ID repositories params
func (o *PostProjectProjectIDRepositoriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post project project ID repositories params
func (o *PostProjectProjectIDRepositoriesParams) WithHTTPClient(client *http.Client) *PostProjectProjectIDRepositoriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post project project ID repositories params
func (o *PostProjectProjectIDRepositoriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepository adds the repository to the post project project ID repositories params
func (o *PostProjectProjectIDRepositoriesParams) WithRepository(repository *models.RepositoryRequest) *PostProjectProjectIDRepositoriesParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the post project project ID repositories params
func (o *PostProjectProjectIDRepositoriesParams) SetRepository(repository *models.RepositoryRequest) {
	o.Repository = repository
}

// WithProjectID adds the projectID to the post project project ID repositories params
func (o *PostProjectProjectIDRepositoriesParams) WithProjectID(projectID int64) *PostProjectProjectIDRepositoriesParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the post project project ID repositories params
func (o *PostProjectProjectIDRepositoriesParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *PostProjectProjectIDRepositoriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Repository != nil {
		if err := r.SetBodyParam(o.Repository); err != nil {
			return err
		}
	}

	// path param project_id
	if err := r.SetPathParam("project_id", swag.FormatInt64(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
