// Code generated by go-swagger; DO NOT EDIT.

package repository

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new repository API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new repository API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new repository API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for repository API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// This client is generated with a few options you might find useful for your swagger spec.
//
// Feel free to add you own set of options.

// WithAccept allows the client to force the Accept header
// to negotiate a specific Producer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithAccept(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ProducesMediaTypes = []string{mime}
	}
}

// WithAcceptApplicationJSON sets the Accept header to "application/json".
func WithAcceptApplicationJSON(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/json"}
}

// WithAcceptTextPlainCharsetUTF8 sets the Accept header to "text/plain; charset=utf-8".
func WithAcceptTextPlainCharsetUTF8(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"text/plain; charset=utf-8"}
}

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteProjectProjectIDRepositoriesRepositoryID(params *DeleteProjectProjectIDRepositoriesRepositoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectProjectIDRepositoriesRepositoryIDNoContent, error)

	GetProjectProjectIDRepositories(params *GetProjectProjectIDRepositoriesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDRepositoriesOK, error)

	GetProjectProjectIDRepositoriesRepositoryID(params *GetProjectProjectIDRepositoriesRepositoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDRepositoriesRepositoryIDOK, error)

	PostProjectProjectIDRepositories(params *PostProjectProjectIDRepositoriesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProjectProjectIDRepositoriesCreated, error)

	PutProjectProjectIDRepositoriesRepositoryID(params *PutProjectProjectIDRepositoriesRepositoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProjectProjectIDRepositoriesRepositoryIDNoContent, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteProjectProjectIDRepositoriesRepositoryID removes repository
*/
func (a *Client) DeleteProjectProjectIDRepositoriesRepositoryID(params *DeleteProjectProjectIDRepositoriesRepositoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectProjectIDRepositoriesRepositoryIDNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteProjectProjectIDRepositoriesRepositoryIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteProjectProjectIDRepositoriesRepositoryID",
		Method:             "DELETE",
		PathPattern:        "/project/{project_id}/repositories/{repository_id}",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteProjectProjectIDRepositoriesRepositoryIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteProjectProjectIDRepositoriesRepositoryIDNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteProjectProjectIDRepositoriesRepositoryID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetProjectProjectIDRepositories gets repositories
*/
func (a *Client) GetProjectProjectIDRepositories(params *GetProjectProjectIDRepositoriesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDRepositoriesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProjectProjectIDRepositoriesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProjectProjectIDRepositories",
		Method:             "GET",
		PathPattern:        "/project/{project_id}/repositories",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetProjectProjectIDRepositoriesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProjectProjectIDRepositoriesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetProjectProjectIDRepositories: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetProjectProjectIDRepositoriesRepositoryID gets repository
*/
func (a *Client) GetProjectProjectIDRepositoriesRepositoryID(params *GetProjectProjectIDRepositoriesRepositoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDRepositoriesRepositoryIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProjectProjectIDRepositoriesRepositoryIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProjectProjectIDRepositoriesRepositoryID",
		Method:             "GET",
		PathPattern:        "/project/{project_id}/repositories/{repository_id}",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetProjectProjectIDRepositoriesRepositoryIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProjectProjectIDRepositoriesRepositoryIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetProjectProjectIDRepositoriesRepositoryID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostProjectProjectIDRepositories adds repository
*/
func (a *Client) PostProjectProjectIDRepositories(params *PostProjectProjectIDRepositoriesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProjectProjectIDRepositoriesCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostProjectProjectIDRepositoriesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostProjectProjectIDRepositories",
		Method:             "POST",
		PathPattern:        "/project/{project_id}/repositories",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PostProjectProjectIDRepositoriesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostProjectProjectIDRepositoriesCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostProjectProjectIDRepositories: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutProjectProjectIDRepositoriesRepositoryID updates repository
*/
func (a *Client) PutProjectProjectIDRepositoriesRepositoryID(params *PutProjectProjectIDRepositoriesRepositoryIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProjectProjectIDRepositoriesRepositoryIDNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutProjectProjectIDRepositoriesRepositoryIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutProjectProjectIDRepositoriesRepositoryID",
		Method:             "PUT",
		PathPattern:        "/project/{project_id}/repositories/{repository_id}",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PutProjectProjectIDRepositoriesRepositoryIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutProjectProjectIDRepositoriesRepositoryIDNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutProjectProjectIDRepositoriesRepositoryID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
