// Code generated by go-swagger; DO NOT EDIT.

package schedule

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"terraform-provider-semaphoreui/semaphoreui/models"
)

// PostProjectProjectIDSchedulesReader is a Reader for the PostProjectProjectIDSchedules structure.
type PostProjectProjectIDSchedulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostProjectProjectIDSchedulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewPostProjectProjectIDSchedulesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /project/{project_id}/schedules] PostProjectProjectIDSchedules", response, response.Code())
	}
}

// NewPostProjectProjectIDSchedulesCreated creates a PostProjectProjectIDSchedulesCreated with default headers values
func NewPostProjectProjectIDSchedulesCreated() *PostProjectProjectIDSchedulesCreated {
	return &PostProjectProjectIDSchedulesCreated{}
}

/*
PostProjectProjectIDSchedulesCreated describes a response with status code 201, with default header values.

schedule created
*/
type PostProjectProjectIDSchedulesCreated struct {
	Payload *models.Schedule
}

// IsSuccess returns true when this post project project Id schedules created response has a 2xx status code
func (o *PostProjectProjectIDSchedulesCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post project project Id schedules created response has a 3xx status code
func (o *PostProjectProjectIDSchedulesCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post project project Id schedules created response has a 4xx status code
func (o *PostProjectProjectIDSchedulesCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post project project Id schedules created response has a 5xx status code
func (o *PostProjectProjectIDSchedulesCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post project project Id schedules created response a status code equal to that given
func (o *PostProjectProjectIDSchedulesCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post project project Id schedules created response
func (o *PostProjectProjectIDSchedulesCreated) Code() int {
	return 201
}

func (o *PostProjectProjectIDSchedulesCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /project/{project_id}/schedules][%d] postProjectProjectIdSchedulesCreated %s", 201, payload)
}

func (o *PostProjectProjectIDSchedulesCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /project/{project_id}/schedules][%d] postProjectProjectIdSchedulesCreated %s", 201, payload)
}

func (o *PostProjectProjectIDSchedulesCreated) GetPayload() *models.Schedule {
	return o.Payload
}

func (o *PostProjectProjectIDSchedulesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Schedule)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
