// Code generated by go-swagger; DO NOT EDIT.

package integration

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewDeleteProjectProjectIDIntegrationsIntegrationIDParams creates a new DeleteProjectProjectIDIntegrationsIntegrationIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteProjectProjectIDIntegrationsIntegrationIDParams() *DeleteProjectProjectIDIntegrationsIntegrationIDParams {
	return NewDeleteProjectProjectIDIntegrationsIntegrationIDParamsWithTimeout(cr.DefaultTimeout)
}

// NewDeleteProjectProjectIDIntegrationsIntegrationIDParamsWithTimeout creates a new DeleteProjectProjectIDIntegrationsIntegrationIDParams object
// with the ability to set a timeout on a request.
func NewDeleteProjectProjectIDIntegrationsIntegrationIDParamsWithTimeout(timeout time.Duration) *DeleteProjectProjectIDIntegrationsIntegrationIDParams {
	return &DeleteProjectProjectIDIntegrationsIntegrationIDParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDeleteProjectProjectIDIntegrationsIntegrationIDParamsWithContext creates a new DeleteProjectProjectIDIntegrationsIntegrationIDParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteProjectProjectIDIntegrationsIntegrationIDParams].
func NewDeleteProjectProjectIDIntegrationsIntegrationIDParamsWithContext(ctx context.Context) *DeleteProjectProjectIDIntegrationsIntegrationIDParams {
	return &DeleteProjectProjectIDIntegrationsIntegrationIDParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDeleteProjectProjectIDIntegrationsIntegrationIDParamsWithHTTPClient creates a new DeleteProjectProjectIDIntegrationsIntegrationIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteProjectProjectIDIntegrationsIntegrationIDParamsWithHTTPClient(client *http.Client) *DeleteProjectProjectIDIntegrationsIntegrationIDParams {
	return &DeleteProjectProjectIDIntegrationsIntegrationIDParams{
		HTTPClient: client,
	}
}

/*
DeleteProjectProjectIDIntegrationsIntegrationIDParams contains all the parameters to send to the API endpoint

	for the delete project project ID integrations integration ID operation.

	Typically these are written to a http.Request.
*/
type DeleteProjectProjectIDIntegrationsIntegrationIDParams struct {

	/* IntegrationID.

	   integration ID
	*/
	IntegrationID int64

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the delete project project ID integrations integration ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDParams) WithDefaults() *DeleteProjectProjectIDIntegrationsIntegrationIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete project project ID integrations integration ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete project project ID integrations integration ID params.
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDParams) WithTimeout(timeout time.Duration) *DeleteProjectProjectIDIntegrationsIntegrationIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete project project ID integrations integration ID params.
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the delete project project ID integrations integration ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteProjectProjectIDIntegrationsIntegrationIDParams].
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDParams) WithContext(ctx context.Context) *DeleteProjectProjectIDIntegrationsIntegrationIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete project project ID integrations integration ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteProjectProjectIDIntegrationsIntegrationIDParams].
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the delete project project ID integrations integration ID params.
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDParams) WithHTTPClient(client *http.Client) *DeleteProjectProjectIDIntegrationsIntegrationIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete project project ID integrations integration ID params.
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIntegrationID adds the integrationID to the delete project project ID integrations integration ID params.
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDParams) WithIntegrationID(integrationID int64) *DeleteProjectProjectIDIntegrationsIntegrationIDParams {
	o.SetIntegrationID(integrationID)
	return o
}

// SetIntegrationID adds the integrationId to the delete project project ID integrations integration ID params.
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDParams) SetIntegrationID(integrationID int64) {
	o.IntegrationID = integrationID
}

// WithProjectID adds the projectID to the delete project project ID integrations integration ID params.
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDParams) WithProjectID(projectID int64) *DeleteProjectProjectIDIntegrationsIntegrationIDParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the delete project project ID integrations integration ID params.
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param integration_id
	if err := r.SetPathParam("integration_id", conv.FormatInteger(o.IntegrationID)); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", conv.FormatInteger(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
