// Code generated by go-swagger; DO NOT EDIT.

package integration

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams creates a new DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams() *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	return &DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParamsWithTimeout creates a new DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams object
// with the ability to set a timeout on a request.
func NewDeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParamsWithTimeout(timeout time.Duration) *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	return &DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams{
		timeout: timeout,
	}
}

// NewDeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParamsWithContext creates a new DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams object
// with the ability to set a context for a request.
func NewDeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParamsWithContext(ctx context.Context) *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	return &DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams{
		Context: ctx,
	}
}

// NewDeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParamsWithHTTPClient creates a new DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParamsWithHTTPClient(client *http.Client) *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	return &DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams{
		HTTPClient: client,
	}
}

/*
DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams contains all the parameters to send to the API endpoint

	for the delete project project ID integrations integration ID matchers matcher ID operation.

	Typically these are written to a http.Request.
*/
type DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams struct {

	/* IntegrationID.

	   integration ID
	*/
	IntegrationID int64

	/* MatcherID.

	   matcher ID
	*/
	MatcherID int64

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete project project ID integrations integration ID matchers matcher ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) WithDefaults() *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete project project ID integrations integration ID matchers matcher ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete project project ID integrations integration ID matchers matcher ID params
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) WithTimeout(timeout time.Duration) *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete project project ID integrations integration ID matchers matcher ID params
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete project project ID integrations integration ID matchers matcher ID params
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) WithContext(ctx context.Context) *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete project project ID integrations integration ID matchers matcher ID params
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete project project ID integrations integration ID matchers matcher ID params
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) WithHTTPClient(client *http.Client) *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete project project ID integrations integration ID matchers matcher ID params
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIntegrationID adds the integrationID to the delete project project ID integrations integration ID matchers matcher ID params
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) WithIntegrationID(integrationID int64) *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	o.SetIntegrationID(integrationID)
	return o
}

// SetIntegrationID adds the integrationId to the delete project project ID integrations integration ID matchers matcher ID params
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) SetIntegrationID(integrationID int64) {
	o.IntegrationID = integrationID
}

// WithMatcherID adds the matcherID to the delete project project ID integrations integration ID matchers matcher ID params
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) WithMatcherID(matcherID int64) *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	o.SetMatcherID(matcherID)
	return o
}

// SetMatcherID adds the matcherId to the delete project project ID integrations integration ID matchers matcher ID params
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) SetMatcherID(matcherID int64) {
	o.MatcherID = matcherID
}

// WithProjectID adds the projectID to the delete project project ID integrations integration ID matchers matcher ID params
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) WithProjectID(projectID int64) *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the delete project project ID integrations integration ID matchers matcher ID params
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param integration_id
	if err := r.SetPathParam("integration_id", swag.FormatInt64(o.IntegrationID)); err != nil {
		return err
	}

	// path param matcher_id
	if err := r.SetPathParam("matcher_id", swag.FormatInt64(o.MatcherID)); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", swag.FormatInt64(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
