// Code generated by go-swagger; DO NOT EDIT.

package integration

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"terraform-provider-semaphoreui/semaphoreui/models"
)

// GetProjectProjectIDIntegrationsIntegrationIDValuesReader is a Reader for the GetProjectProjectIDIntegrationsIntegrationIDValues structure.
type GetProjectProjectIDIntegrationsIntegrationIDValuesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectProjectIDIntegrationsIntegrationIDValuesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectProjectIDIntegrationsIntegrationIDValuesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /project/{project_id}/integrations/{integration_id}/values] GetProjectProjectIDIntegrationsIntegrationIDValues", response, response.Code())
	}
}

// NewGetProjectProjectIDIntegrationsIntegrationIDValuesOK creates a GetProjectProjectIDIntegrationsIntegrationIDValuesOK with default headers values
func NewGetProjectProjectIDIntegrationsIntegrationIDValuesOK() *GetProjectProjectIDIntegrationsIntegrationIDValuesOK {
	return &GetProjectProjectIDIntegrationsIntegrationIDValuesOK{}
}

/*
GetProjectProjectIDIntegrationsIntegrationIDValuesOK describes a response with status code 200, with default header values.

Integration Extracted Value
*/
type GetProjectProjectIDIntegrationsIntegrationIDValuesOK struct {
	Payload []*models.IntegrationExtractValue
}

// IsSuccess returns true when this get project project Id integrations integration Id values o k response has a 2xx status code
func (o *GetProjectProjectIDIntegrationsIntegrationIDValuesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get project project Id integrations integration Id values o k response has a 3xx status code
func (o *GetProjectProjectIDIntegrationsIntegrationIDValuesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project project Id integrations integration Id values o k response has a 4xx status code
func (o *GetProjectProjectIDIntegrationsIntegrationIDValuesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get project project Id integrations integration Id values o k response has a 5xx status code
func (o *GetProjectProjectIDIntegrationsIntegrationIDValuesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get project project Id integrations integration Id values o k response a status code equal to that given
func (o *GetProjectProjectIDIntegrationsIntegrationIDValuesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get project project Id integrations integration Id values o k response
func (o *GetProjectProjectIDIntegrationsIntegrationIDValuesOK) Code() int {
	return 200
}

func (o *GetProjectProjectIDIntegrationsIntegrationIDValuesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{project_id}/integrations/{integration_id}/values][%d] getProjectProjectIdIntegrationsIntegrationIdValuesOK %s", 200, payload)
}

func (o *GetProjectProjectIDIntegrationsIntegrationIDValuesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{project_id}/integrations/{integration_id}/values][%d] getProjectProjectIdIntegrationsIntegrationIdValuesOK %s", 200, payload)
}

func (o *GetProjectProjectIDIntegrationsIntegrationIDValuesOK) GetPayload() []*models.IntegrationExtractValue {
	return o.Payload
}

func (o *GetProjectProjectIDIntegrationsIntegrationIDValuesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
