// Code generated by go-swagger; DO NOT EDIT.

package integration

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"terraform-provider-semaphoreui/semaphoreui/models"
)

// GetProjectProjectIDIntegrationsIntegrationIDReader is a Reader for the GetProjectProjectIDIntegrationsIntegrationID structure.
type GetProjectProjectIDIntegrationsIntegrationIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectProjectIDIntegrationsIntegrationIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectProjectIDIntegrationsIntegrationIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /project/{project_id}/integrations/{integration_id}] GetProjectProjectIDIntegrationsIntegrationID", response, response.Code())
	}
}

// NewGetProjectProjectIDIntegrationsIntegrationIDOK creates a GetProjectProjectIDIntegrationsIntegrationIDOK with default headers values
func NewGetProjectProjectIDIntegrationsIntegrationIDOK() *GetProjectProjectIDIntegrationsIntegrationIDOK {
	return &GetProjectProjectIDIntegrationsIntegrationIDOK{}
}

/*
GetProjectProjectIDIntegrationsIntegrationIDOK describes a response with status code 200, with default header values.

Integration Value
*/
type GetProjectProjectIDIntegrationsIntegrationIDOK struct {
	Payload *models.Integration
}

// IsSuccess returns true when this get project project Id integrations integration Id o k response has a 2xx status code
func (o *GetProjectProjectIDIntegrationsIntegrationIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get project project Id integrations integration Id o k response has a 3xx status code
func (o *GetProjectProjectIDIntegrationsIntegrationIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project project Id integrations integration Id o k response has a 4xx status code
func (o *GetProjectProjectIDIntegrationsIntegrationIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get project project Id integrations integration Id o k response has a 5xx status code
func (o *GetProjectProjectIDIntegrationsIntegrationIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get project project Id integrations integration Id o k response a status code equal to that given
func (o *GetProjectProjectIDIntegrationsIntegrationIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get project project Id integrations integration Id o k response
func (o *GetProjectProjectIDIntegrationsIntegrationIDOK) Code() int {
	return 200
}

func (o *GetProjectProjectIDIntegrationsIntegrationIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{project_id}/integrations/{integration_id}][%d] getProjectProjectIdIntegrationsIntegrationIdOK %s", 200, payload)
}

func (o *GetProjectProjectIDIntegrationsIntegrationIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{project_id}/integrations/{integration_id}][%d] getProjectProjectIdIntegrationsIntegrationIdOK %s", 200, payload)
}

func (o *GetProjectProjectIDIntegrationsIntegrationIDOK) GetPayload() *models.Integration {
	return o.Payload
}

func (o *GetProjectProjectIDIntegrationsIntegrationIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Integration)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
