// Code generated by go-swagger; DO NOT EDIT.

package integration

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetProjectProjectIDIntegrationsParams creates a new GetProjectProjectIDIntegrationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectProjectIDIntegrationsParams() *GetProjectProjectIDIntegrationsParams {
	return &GetProjectProjectIDIntegrationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProjectProjectIDIntegrationsParamsWithTimeout creates a new GetProjectProjectIDIntegrationsParams object
// with the ability to set a timeout on a request.
func NewGetProjectProjectIDIntegrationsParamsWithTimeout(timeout time.Duration) *GetProjectProjectIDIntegrationsParams {
	return &GetProjectProjectIDIntegrationsParams{
		timeout: timeout,
	}
}

// NewGetProjectProjectIDIntegrationsParamsWithContext creates a new GetProjectProjectIDIntegrationsParams object
// with the ability to set a context for a request.
func NewGetProjectProjectIDIntegrationsParamsWithContext(ctx context.Context) *GetProjectProjectIDIntegrationsParams {
	return &GetProjectProjectIDIntegrationsParams{
		Context: ctx,
	}
}

// NewGetProjectProjectIDIntegrationsParamsWithHTTPClient creates a new GetProjectProjectIDIntegrationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectProjectIDIntegrationsParamsWithHTTPClient(client *http.Client) *GetProjectProjectIDIntegrationsParams {
	return &GetProjectProjectIDIntegrationsParams{
		HTTPClient: client,
	}
}

/*
GetProjectProjectIDIntegrationsParams contains all the parameters to send to the API endpoint

	for the get project project ID integrations operation.

	Typically these are written to a http.Request.
*/
type GetProjectProjectIDIntegrationsParams struct {

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get project project ID integrations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectProjectIDIntegrationsParams) WithDefaults() *GetProjectProjectIDIntegrationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get project project ID integrations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectProjectIDIntegrationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get project project ID integrations params
func (o *GetProjectProjectIDIntegrationsParams) WithTimeout(timeout time.Duration) *GetProjectProjectIDIntegrationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project project ID integrations params
func (o *GetProjectProjectIDIntegrationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get project project ID integrations params
func (o *GetProjectProjectIDIntegrationsParams) WithContext(ctx context.Context) *GetProjectProjectIDIntegrationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project project ID integrations params
func (o *GetProjectProjectIDIntegrationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get project project ID integrations params
func (o *GetProjectProjectIDIntegrationsParams) WithHTTPClient(client *http.Client) *GetProjectProjectIDIntegrationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project project ID integrations params
func (o *GetProjectProjectIDIntegrationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectID adds the projectID to the get project project ID integrations params
func (o *GetProjectProjectIDIntegrationsParams) WithProjectID(projectID int64) *GetProjectProjectIDIntegrationsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get project project ID integrations params
func (o *GetProjectProjectIDIntegrationsParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *GetProjectProjectIDIntegrationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param project_id
	if err := r.SetPathParam("project_id", swag.FormatInt64(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
