// Code generated by go-swagger; DO NOT EDIT.

package integration

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"terraform-provider-semaphoreui/semaphoreui/models"
)

// GetProjectProjectIDIntegrationsReader is a Reader for the GetProjectProjectIDIntegrations structure.
type GetProjectProjectIDIntegrationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectProjectIDIntegrationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectProjectIDIntegrationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /project/{project_id}/integrations] GetProjectProjectIDIntegrations", response, response.Code())
	}
}

// NewGetProjectProjectIDIntegrationsOK creates a GetProjectProjectIDIntegrationsOK with default headers values
func NewGetProjectProjectIDIntegrationsOK() *GetProjectProjectIDIntegrationsOK {
	return &GetProjectProjectIDIntegrationsOK{}
}

/*
GetProjectProjectIDIntegrationsOK describes a response with status code 200, with default header values.

integration
*/
type GetProjectProjectIDIntegrationsOK struct {
	Payload []*models.Integration
}

// IsSuccess returns true when this get project project Id integrations o k response has a 2xx status code
func (o *GetProjectProjectIDIntegrationsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get project project Id integrations o k response has a 3xx status code
func (o *GetProjectProjectIDIntegrationsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project project Id integrations o k response has a 4xx status code
func (o *GetProjectProjectIDIntegrationsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get project project Id integrations o k response has a 5xx status code
func (o *GetProjectProjectIDIntegrationsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get project project Id integrations o k response a status code equal to that given
func (o *GetProjectProjectIDIntegrationsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get project project Id integrations o k response
func (o *GetProjectProjectIDIntegrationsOK) Code() int {
	return 200
}

func (o *GetProjectProjectIDIntegrationsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{project_id}/integrations][%d] getProjectProjectIdIntegrationsOK %s", 200, payload)
}

func (o *GetProjectProjectIDIntegrationsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{project_id}/integrations][%d] getProjectProjectIdIntegrationsOK %s", 200, payload)
}

func (o *GetProjectProjectIDIntegrationsOK) GetPayload() []*models.Integration {
	return o.Payload
}

func (o *GetProjectProjectIDIntegrationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
