// Code generated by go-swagger; DO NOT EDIT.

package integration

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"terraform-provider-semaphoreui/semaphoreui/models"
)

// NewPostProjectProjectIDIntegrationsIntegrationIDValuesParams creates a new PostProjectProjectIDIntegrationsIntegrationIDValuesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostProjectProjectIDIntegrationsIntegrationIDValuesParams() *PostProjectProjectIDIntegrationsIntegrationIDValuesParams {
	return &PostProjectProjectIDIntegrationsIntegrationIDValuesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostProjectProjectIDIntegrationsIntegrationIDValuesParamsWithTimeout creates a new PostProjectProjectIDIntegrationsIntegrationIDValuesParams object
// with the ability to set a timeout on a request.
func NewPostProjectProjectIDIntegrationsIntegrationIDValuesParamsWithTimeout(timeout time.Duration) *PostProjectProjectIDIntegrationsIntegrationIDValuesParams {
	return &PostProjectProjectIDIntegrationsIntegrationIDValuesParams{
		timeout: timeout,
	}
}

// NewPostProjectProjectIDIntegrationsIntegrationIDValuesParamsWithContext creates a new PostProjectProjectIDIntegrationsIntegrationIDValuesParams object
// with the ability to set a context for a request.
func NewPostProjectProjectIDIntegrationsIntegrationIDValuesParamsWithContext(ctx context.Context) *PostProjectProjectIDIntegrationsIntegrationIDValuesParams {
	return &PostProjectProjectIDIntegrationsIntegrationIDValuesParams{
		Context: ctx,
	}
}

// NewPostProjectProjectIDIntegrationsIntegrationIDValuesParamsWithHTTPClient creates a new PostProjectProjectIDIntegrationsIntegrationIDValuesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostProjectProjectIDIntegrationsIntegrationIDValuesParamsWithHTTPClient(client *http.Client) *PostProjectProjectIDIntegrationsIntegrationIDValuesParams {
	return &PostProjectProjectIDIntegrationsIntegrationIDValuesParams{
		HTTPClient: client,
	}
}

/*
PostProjectProjectIDIntegrationsIntegrationIDValuesParams contains all the parameters to send to the API endpoint

	for the post project project ID integrations integration ID values operation.

	Typically these are written to a http.Request.
*/
type PostProjectProjectIDIntegrationsIntegrationIDValuesParams struct {

	// IntegrationExtractedValue.
	IntegrationExtractedValue *models.IntegrationExtractValue

	/* IntegrationID.

	   integration ID
	*/
	IntegrationID int64

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post project project ID integrations integration ID values params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProjectProjectIDIntegrationsIntegrationIDValuesParams) WithDefaults() *PostProjectProjectIDIntegrationsIntegrationIDValuesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post project project ID integrations integration ID values params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProjectProjectIDIntegrationsIntegrationIDValuesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post project project ID integrations integration ID values params
func (o *PostProjectProjectIDIntegrationsIntegrationIDValuesParams) WithTimeout(timeout time.Duration) *PostProjectProjectIDIntegrationsIntegrationIDValuesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post project project ID integrations integration ID values params
func (o *PostProjectProjectIDIntegrationsIntegrationIDValuesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post project project ID integrations integration ID values params
func (o *PostProjectProjectIDIntegrationsIntegrationIDValuesParams) WithContext(ctx context.Context) *PostProjectProjectIDIntegrationsIntegrationIDValuesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post project project ID integrations integration ID values params
func (o *PostProjectProjectIDIntegrationsIntegrationIDValuesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post project project ID integrations integration ID values params
func (o *PostProjectProjectIDIntegrationsIntegrationIDValuesParams) WithHTTPClient(client *http.Client) *PostProjectProjectIDIntegrationsIntegrationIDValuesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post project project ID integrations integration ID values params
func (o *PostProjectProjectIDIntegrationsIntegrationIDValuesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIntegrationExtractedValue adds the integrationExtractedValue to the post project project ID integrations integration ID values params
func (o *PostProjectProjectIDIntegrationsIntegrationIDValuesParams) WithIntegrationExtractedValue(integrationExtractedValue *models.IntegrationExtractValue) *PostProjectProjectIDIntegrationsIntegrationIDValuesParams {
	o.SetIntegrationExtractedValue(integrationExtractedValue)
	return o
}

// SetIntegrationExtractedValue adds the integrationExtractedValue to the post project project ID integrations integration ID values params
func (o *PostProjectProjectIDIntegrationsIntegrationIDValuesParams) SetIntegrationExtractedValue(integrationExtractedValue *models.IntegrationExtractValue) {
	o.IntegrationExtractedValue = integrationExtractedValue
}

// WithIntegrationID adds the integrationID to the post project project ID integrations integration ID values params
func (o *PostProjectProjectIDIntegrationsIntegrationIDValuesParams) WithIntegrationID(integrationID int64) *PostProjectProjectIDIntegrationsIntegrationIDValuesParams {
	o.SetIntegrationID(integrationID)
	return o
}

// SetIntegrationID adds the integrationId to the post project project ID integrations integration ID values params
func (o *PostProjectProjectIDIntegrationsIntegrationIDValuesParams) SetIntegrationID(integrationID int64) {
	o.IntegrationID = integrationID
}

// WithProjectID adds the projectID to the post project project ID integrations integration ID values params
func (o *PostProjectProjectIDIntegrationsIntegrationIDValuesParams) WithProjectID(projectID int64) *PostProjectProjectIDIntegrationsIntegrationIDValuesParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the post project project ID integrations integration ID values params
func (o *PostProjectProjectIDIntegrationsIntegrationIDValuesParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *PostProjectProjectIDIntegrationsIntegrationIDValuesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.IntegrationExtractedValue != nil {
		if err := r.SetBodyParam(o.IntegrationExtractedValue); err != nil {
			return err
		}
	}

	// path param integration_id
	if err := r.SetPathParam("integration_id", swag.FormatInt64(o.IntegrationID)); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", swag.FormatInt64(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
