// Code generated by go-swagger; DO NOT EDIT.

package integration

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDReader is a Reader for the PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherID structure.
type PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewPutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /project/{project_id}/integrations/{integration_id}/matchers/{matcher_id}] PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherID", response, response.Code())
	}
}

// NewPutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDNoContent creates a PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDNoContent with default headers values
func NewPutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDNoContent() *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDNoContent {
	return &PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDNoContent{}
}

/*
PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDNoContent describes a response with status code 204, with default header values.

Integration Matcher updated
*/
type PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDNoContent struct {
}

// IsSuccess returns true when this put project project Id integrations integration Id matchers matcher Id no content response has a 2xx status code
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put project project Id integrations integration Id matchers matcher Id no content response has a 3xx status code
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put project project Id integrations integration Id matchers matcher Id no content response has a 4xx status code
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this put project project Id integrations integration Id matchers matcher Id no content response has a 5xx status code
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this put project project Id integrations integration Id matchers matcher Id no content response a status code equal to that given
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the put project project Id integrations integration Id matchers matcher Id no content response
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDNoContent) Code() int {
	return 204
}

func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDNoContent) Error() string {
	return fmt.Sprintf("[PUT /project/{project_id}/integrations/{integration_id}/matchers/{matcher_id}][%d] putProjectProjectIdIntegrationsIntegrationIdMatchersMatcherIdNoContent", 204)
}

func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDNoContent) String() string {
	return fmt.Sprintf("[PUT /project/{project_id}/integrations/{integration_id}/matchers/{matcher_id}][%d] putProjectProjectIdIntegrationsIntegrationIdMatchersMatcherIdNoContent", 204)
}

func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDBadRequest creates a PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDBadRequest with default headers values
func NewPutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDBadRequest() *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDBadRequest {
	return &PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDBadRequest{}
}

/*
PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDBadRequest describes a response with status code 400, with default header values.

Bad integration matcher parameter
*/
type PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDBadRequest struct {
}

// IsSuccess returns true when this put project project Id integrations integration Id matchers matcher Id bad request response has a 2xx status code
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put project project Id integrations integration Id matchers matcher Id bad request response has a 3xx status code
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put project project Id integrations integration Id matchers matcher Id bad request response has a 4xx status code
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put project project Id integrations integration Id matchers matcher Id bad request response has a 5xx status code
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put project project Id integrations integration Id matchers matcher Id bad request response a status code equal to that given
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put project project Id integrations integration Id matchers matcher Id bad request response
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDBadRequest) Code() int {
	return 400
}

func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /project/{project_id}/integrations/{integration_id}/matchers/{matcher_id}][%d] putProjectProjectIdIntegrationsIntegrationIdMatchersMatcherIdBadRequest", 400)
}

func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDBadRequest) String() string {
	return fmt.Sprintf("[PUT /project/{project_id}/integrations/{integration_id}/matchers/{matcher_id}][%d] putProjectProjectIdIntegrationsIntegrationIdMatchersMatcherIdBadRequest", 400)
}

func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
