// Code generated by go-swagger; DO NOT EDIT.

package integration

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"terraform-provider-semaphoreui/semaphoreui/models"
)

// NewPutProjectProjectIDIntegrationsIntegrationIDParams creates a new PutProjectProjectIDIntegrationsIntegrationIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutProjectProjectIDIntegrationsIntegrationIDParams() *PutProjectProjectIDIntegrationsIntegrationIDParams {
	return &PutProjectProjectIDIntegrationsIntegrationIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutProjectProjectIDIntegrationsIntegrationIDParamsWithTimeout creates a new PutProjectProjectIDIntegrationsIntegrationIDParams object
// with the ability to set a timeout on a request.
func NewPutProjectProjectIDIntegrationsIntegrationIDParamsWithTimeout(timeout time.Duration) *PutProjectProjectIDIntegrationsIntegrationIDParams {
	return &PutProjectProjectIDIntegrationsIntegrationIDParams{
		timeout: timeout,
	}
}

// NewPutProjectProjectIDIntegrationsIntegrationIDParamsWithContext creates a new PutProjectProjectIDIntegrationsIntegrationIDParams object
// with the ability to set a context for a request.
func NewPutProjectProjectIDIntegrationsIntegrationIDParamsWithContext(ctx context.Context) *PutProjectProjectIDIntegrationsIntegrationIDParams {
	return &PutProjectProjectIDIntegrationsIntegrationIDParams{
		Context: ctx,
	}
}

// NewPutProjectProjectIDIntegrationsIntegrationIDParamsWithHTTPClient creates a new PutProjectProjectIDIntegrationsIntegrationIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutProjectProjectIDIntegrationsIntegrationIDParamsWithHTTPClient(client *http.Client) *PutProjectProjectIDIntegrationsIntegrationIDParams {
	return &PutProjectProjectIDIntegrationsIntegrationIDParams{
		HTTPClient: client,
	}
}

/*
PutProjectProjectIDIntegrationsIntegrationIDParams contains all the parameters to send to the API endpoint

	for the put project project ID integrations integration ID operation.

	Typically these are written to a http.Request.
*/
type PutProjectProjectIDIntegrationsIntegrationIDParams struct {

	// Integration.
	Integration *models.IntegrationRequest

	/* IntegrationID.

	   integration ID
	*/
	IntegrationID int64

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put project project ID integrations integration ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProjectProjectIDIntegrationsIntegrationIDParams) WithDefaults() *PutProjectProjectIDIntegrationsIntegrationIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put project project ID integrations integration ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProjectProjectIDIntegrationsIntegrationIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put project project ID integrations integration ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDParams) WithTimeout(timeout time.Duration) *PutProjectProjectIDIntegrationsIntegrationIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put project project ID integrations integration ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put project project ID integrations integration ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDParams) WithContext(ctx context.Context) *PutProjectProjectIDIntegrationsIntegrationIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put project project ID integrations integration ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put project project ID integrations integration ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDParams) WithHTTPClient(client *http.Client) *PutProjectProjectIDIntegrationsIntegrationIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put project project ID integrations integration ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIntegration adds the integration to the put project project ID integrations integration ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDParams) WithIntegration(integration *models.IntegrationRequest) *PutProjectProjectIDIntegrationsIntegrationIDParams {
	o.SetIntegration(integration)
	return o
}

// SetIntegration adds the integration to the put project project ID integrations integration ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDParams) SetIntegration(integration *models.IntegrationRequest) {
	o.Integration = integration
}

// WithIntegrationID adds the integrationID to the put project project ID integrations integration ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDParams) WithIntegrationID(integrationID int64) *PutProjectProjectIDIntegrationsIntegrationIDParams {
	o.SetIntegrationID(integrationID)
	return o
}

// SetIntegrationID adds the integrationId to the put project project ID integrations integration ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDParams) SetIntegrationID(integrationID int64) {
	o.IntegrationID = integrationID
}

// WithProjectID adds the projectID to the put project project ID integrations integration ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDParams) WithProjectID(projectID int64) *PutProjectProjectIDIntegrationsIntegrationIDParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the put project project ID integrations integration ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *PutProjectProjectIDIntegrationsIntegrationIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Integration != nil {
		if err := r.SetBodyParam(o.Integration); err != nil {
			return err
		}
	}

	// path param integration_id
	if err := r.SetPathParam("integration_id", swag.FormatInt64(o.IntegrationID)); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", swag.FormatInt64(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
