// Code generated by go-swagger; DO NOT EDIT.

package integration

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"terraform-provider-semaphoreui/semaphoreui/models"
)

// NewPutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams creates a new PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams() *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	return &PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParamsWithTimeout creates a new PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams object
// with the ability to set a timeout on a request.
func NewPutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParamsWithTimeout(timeout time.Duration) *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	return &PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams{
		timeout: timeout,
	}
}

// NewPutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParamsWithContext creates a new PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams object
// with the ability to set a context for a request.
func NewPutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParamsWithContext(ctx context.Context) *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	return &PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams{
		Context: ctx,
	}
}

// NewPutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParamsWithHTTPClient creates a new PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParamsWithHTTPClient(client *http.Client) *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	return &PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams{
		HTTPClient: client,
	}
}

/*
PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams contains all the parameters to send to the API endpoint

	for the put project project ID integrations integration ID matchers matcher ID operation.

	Typically these are written to a http.Request.
*/
type PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams struct {

	// IntegrationMatcher.
	IntegrationMatcher *models.IntegrationMatcherRequest

	/* IntegrationID.

	   integration ID
	*/
	IntegrationID int64

	/* MatcherID.

	   matcher ID
	*/
	MatcherID int64

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put project project ID integrations integration ID matchers matcher ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) WithDefaults() *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put project project ID integrations integration ID matchers matcher ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put project project ID integrations integration ID matchers matcher ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) WithTimeout(timeout time.Duration) *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put project project ID integrations integration ID matchers matcher ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put project project ID integrations integration ID matchers matcher ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) WithContext(ctx context.Context) *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put project project ID integrations integration ID matchers matcher ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put project project ID integrations integration ID matchers matcher ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) WithHTTPClient(client *http.Client) *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put project project ID integrations integration ID matchers matcher ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIntegrationMatcher adds the integrationMatcher to the put project project ID integrations integration ID matchers matcher ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) WithIntegrationMatcher(integrationMatcher *models.IntegrationMatcherRequest) *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	o.SetIntegrationMatcher(integrationMatcher)
	return o
}

// SetIntegrationMatcher adds the integrationMatcher to the put project project ID integrations integration ID matchers matcher ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) SetIntegrationMatcher(integrationMatcher *models.IntegrationMatcherRequest) {
	o.IntegrationMatcher = integrationMatcher
}

// WithIntegrationID adds the integrationID to the put project project ID integrations integration ID matchers matcher ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) WithIntegrationID(integrationID int64) *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	o.SetIntegrationID(integrationID)
	return o
}

// SetIntegrationID adds the integrationId to the put project project ID integrations integration ID matchers matcher ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) SetIntegrationID(integrationID int64) {
	o.IntegrationID = integrationID
}

// WithMatcherID adds the matcherID to the put project project ID integrations integration ID matchers matcher ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) WithMatcherID(matcherID int64) *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	o.SetMatcherID(matcherID)
	return o
}

// SetMatcherID adds the matcherId to the put project project ID integrations integration ID matchers matcher ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) SetMatcherID(matcherID int64) {
	o.MatcherID = matcherID
}

// WithProjectID adds the projectID to the put project project ID integrations integration ID matchers matcher ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) WithProjectID(projectID int64) *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the put project project ID integrations integration ID matchers matcher ID params
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *PutProjectProjectIDIntegrationsIntegrationIDMatchersMatcherIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.IntegrationMatcher != nil {
		if err := r.SetBodyParam(o.IntegrationMatcher); err != nil {
			return err
		}
	}

	// path param integration_id
	if err := r.SetPathParam("integration_id", swag.FormatInt64(o.IntegrationID)); err != nil {
		return err
	}

	// path param matcher_id
	if err := r.SetPathParam("matcher_id", swag.FormatInt64(o.MatcherID)); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", swag.FormatInt64(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
