// Code generated by go-swagger; DO NOT EDIT.

package variable_group

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"terraform-provider-semaphoreui/semaphoreui/models"
)

// GetProjectProjectIDEnvironmentReader is a Reader for the GetProjectProjectIDEnvironment structure.
type GetProjectProjectIDEnvironmentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectProjectIDEnvironmentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectProjectIDEnvironmentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /project/{project_id}/environment] GetProjectProjectIDEnvironment", response, response.Code())
	}
}

// NewGetProjectProjectIDEnvironmentOK creates a GetProjectProjectIDEnvironmentOK with default headers values
func NewGetProjectProjectIDEnvironmentOK() *GetProjectProjectIDEnvironmentOK {
	return &GetProjectProjectIDEnvironmentOK{}
}

/*
GetProjectProjectIDEnvironmentOK describes a response with status code 200, with default header values.

environment
*/
type GetProjectProjectIDEnvironmentOK struct {
	Payload []*models.Environment
}

// IsSuccess returns true when this get project project Id environment o k response has a 2xx status code
func (o *GetProjectProjectIDEnvironmentOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get project project Id environment o k response has a 3xx status code
func (o *GetProjectProjectIDEnvironmentOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project project Id environment o k response has a 4xx status code
func (o *GetProjectProjectIDEnvironmentOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get project project Id environment o k response has a 5xx status code
func (o *GetProjectProjectIDEnvironmentOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get project project Id environment o k response a status code equal to that given
func (o *GetProjectProjectIDEnvironmentOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get project project Id environment o k response
func (o *GetProjectProjectIDEnvironmentOK) Code() int {
	return 200
}

func (o *GetProjectProjectIDEnvironmentOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{project_id}/environment][%d] getProjectProjectIdEnvironmentOK %s", 200, payload)
}

func (o *GetProjectProjectIDEnvironmentOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{project_id}/environment][%d] getProjectProjectIdEnvironmentOK %s", 200, payload)
}

func (o *GetProjectProjectIDEnvironmentOK) GetPayload() []*models.Environment {
	return o.Payload
}

func (o *GetProjectProjectIDEnvironmentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
