// Code generated by go-swagger; DO NOT EDIT.

package variable_group

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new variable group API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new variable group API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new variable group API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for variable group API.
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// This client is generated with a few options you might find useful for your swagger spec.
//
// Feel free to add you own set of options.

// WithAccept allows the client to force the Accept header
// to negotiate a specific Producer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithAccept(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ProducesMediaTypes = []string{mime}
	}
}

// WithAcceptApplicationJSON sets the Accept header to "application/json".
func WithAcceptApplicationJSON(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/json"}
}

// WithAcceptTextPlainCharsetUTF8 sets the Accept header to "text/plain; charset=utf-8".
func WithAcceptTextPlainCharsetUTF8(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"text/plain; charset=utf-8"}
}

// ClientService is the interface for Client methods.
type ClientService interface {

	// DeleteProjectProjectIDEnvironmentEnvironmentID removes environment.
	DeleteProjectProjectIDEnvironmentEnvironmentID(params *DeleteProjectProjectIDEnvironmentEnvironmentIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectProjectIDEnvironmentEnvironmentIDNoContent, error)

	// DeleteProjectProjectIDEnvironmentEnvironmentIDContext removes environment.
	DeleteProjectProjectIDEnvironmentEnvironmentIDContext(ctx context.Context, params *DeleteProjectProjectIDEnvironmentEnvironmentIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectProjectIDEnvironmentEnvironmentIDNoContent, error)

	// GetProjectProjectIDEnvironment get environment.
	GetProjectProjectIDEnvironment(params *GetProjectProjectIDEnvironmentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDEnvironmentOK, error)

	// GetProjectProjectIDEnvironmentContext get environment.
	GetProjectProjectIDEnvironmentContext(ctx context.Context, params *GetProjectProjectIDEnvironmentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDEnvironmentOK, error)

	// GetProjectProjectIDEnvironmentEnvironmentID get environment.
	GetProjectProjectIDEnvironmentEnvironmentID(params *GetProjectProjectIDEnvironmentEnvironmentIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDEnvironmentEnvironmentIDOK, error)

	// GetProjectProjectIDEnvironmentEnvironmentIDContext get environment.
	GetProjectProjectIDEnvironmentEnvironmentIDContext(ctx context.Context, params *GetProjectProjectIDEnvironmentEnvironmentIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDEnvironmentEnvironmentIDOK, error)

	// PostProjectProjectIDEnvironment add environment.
	PostProjectProjectIDEnvironment(params *PostProjectProjectIDEnvironmentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProjectProjectIDEnvironmentCreated, error)

	// PostProjectProjectIDEnvironmentContext add environment.
	PostProjectProjectIDEnvironmentContext(ctx context.Context, params *PostProjectProjectIDEnvironmentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProjectProjectIDEnvironmentCreated, error)

	// PutProjectProjectIDEnvironmentEnvironmentID update environment.
	PutProjectProjectIDEnvironmentEnvironmentID(params *PutProjectProjectIDEnvironmentEnvironmentIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProjectProjectIDEnvironmentEnvironmentIDNoContent, error)

	// PutProjectProjectIDEnvironmentEnvironmentIDContext update environment.
	PutProjectProjectIDEnvironmentEnvironmentIDContext(ctx context.Context, params *PutProjectProjectIDEnvironmentEnvironmentIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProjectProjectIDEnvironmentEnvironmentIDNoContent, error)

	SetTransport(transport runtime.ContextualTransport)
}

/*
DeleteProjectProjectIDEnvironmentEnvironmentIDremoves environment.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.DeleteProjectProjectIDEnvironmentEnvironmentIDContext] instead.
*/
func (a *Client) DeleteProjectProjectIDEnvironmentEnvironmentID(params *DeleteProjectProjectIDEnvironmentEnvironmentIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectProjectIDEnvironmentEnvironmentIDNoContent, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.DeleteProjectProjectIDEnvironmentEnvironmentIDContext(ctx, params, authInfo, opts...)
}

/*
DeleteProjectProjectIDEnvironmentEnvironmentIDContextremoves environment.

Do not use the deprecated [DeleteProjectProjectIDEnvironmentEnvironmentIDParams.Context] with this method: it would be ignored.
*/
func (a *Client) DeleteProjectProjectIDEnvironmentEnvironmentIDContext(ctx context.Context, params *DeleteProjectProjectIDEnvironmentEnvironmentIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectProjectIDEnvironmentEnvironmentIDNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteProjectProjectIDEnvironmentEnvironmentIDParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "DeleteProjectProjectIDEnvironmentEnvironmentID",
		Method:             "DELETE",
		PathPattern:        "/project/{project_id}/environment/{environment_id}",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteProjectProjectIDEnvironmentEnvironmentIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteProjectProjectIDEnvironmentEnvironmentIDNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteProjectProjectIDEnvironmentEnvironmentID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetProjectProjectIDEnvironmentgets environment.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetProjectProjectIDEnvironmentContext] instead.
*/
func (a *Client) GetProjectProjectIDEnvironment(params *GetProjectProjectIDEnvironmentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDEnvironmentOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetProjectProjectIDEnvironmentContext(ctx, params, authInfo, opts...)
}

/*
GetProjectProjectIDEnvironmentContextgets environment.

Do not use the deprecated [GetProjectProjectIDEnvironmentParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetProjectProjectIDEnvironmentContext(ctx context.Context, params *GetProjectProjectIDEnvironmentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDEnvironmentOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProjectProjectIDEnvironmentParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetProjectProjectIDEnvironment",
		Method:             "GET",
		PathPattern:        "/project/{project_id}/environment",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetProjectProjectIDEnvironmentReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProjectProjectIDEnvironmentOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetProjectProjectIDEnvironment: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetProjectProjectIDEnvironmentEnvironmentIDgets environment.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetProjectProjectIDEnvironmentEnvironmentIDContext] instead.
*/
func (a *Client) GetProjectProjectIDEnvironmentEnvironmentID(params *GetProjectProjectIDEnvironmentEnvironmentIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDEnvironmentEnvironmentIDOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetProjectProjectIDEnvironmentEnvironmentIDContext(ctx, params, authInfo, opts...)
}

/*
GetProjectProjectIDEnvironmentEnvironmentIDContextgets environment.

Do not use the deprecated [GetProjectProjectIDEnvironmentEnvironmentIDParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetProjectProjectIDEnvironmentEnvironmentIDContext(ctx context.Context, params *GetProjectProjectIDEnvironmentEnvironmentIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectProjectIDEnvironmentEnvironmentIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProjectProjectIDEnvironmentEnvironmentIDParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetProjectProjectIDEnvironmentEnvironmentID",
		Method:             "GET",
		PathPattern:        "/project/{project_id}/environment/{environment_id}",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetProjectProjectIDEnvironmentEnvironmentIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProjectProjectIDEnvironmentEnvironmentIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetProjectProjectIDEnvironmentEnvironmentID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostProjectProjectIDEnvironmentadds environment.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostProjectProjectIDEnvironmentContext] instead.
*/
func (a *Client) PostProjectProjectIDEnvironment(params *PostProjectProjectIDEnvironmentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProjectProjectIDEnvironmentCreated, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostProjectProjectIDEnvironmentContext(ctx, params, authInfo, opts...)
}

/*
PostProjectProjectIDEnvironmentContextadds environment.

Do not use the deprecated [PostProjectProjectIDEnvironmentParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostProjectProjectIDEnvironmentContext(ctx context.Context, params *PostProjectProjectIDEnvironmentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProjectProjectIDEnvironmentCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostProjectProjectIDEnvironmentParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostProjectProjectIDEnvironment",
		Method:             "POST",
		PathPattern:        "/project/{project_id}/environment",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PostProjectProjectIDEnvironmentReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostProjectProjectIDEnvironmentCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostProjectProjectIDEnvironment: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutProjectProjectIDEnvironmentEnvironmentIDupdates environment.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PutProjectProjectIDEnvironmentEnvironmentIDContext] instead.
*/
func (a *Client) PutProjectProjectIDEnvironmentEnvironmentID(params *PutProjectProjectIDEnvironmentEnvironmentIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProjectProjectIDEnvironmentEnvironmentIDNoContent, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PutProjectProjectIDEnvironmentEnvironmentIDContext(ctx, params, authInfo, opts...)
}

/*
PutProjectProjectIDEnvironmentEnvironmentIDContextupdates environment.

Do not use the deprecated [PutProjectProjectIDEnvironmentEnvironmentIDParams.Context] with this method: it would be ignored.
*/
func (a *Client) PutProjectProjectIDEnvironmentEnvironmentIDContext(ctx context.Context, params *PutProjectProjectIDEnvironmentEnvironmentIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutProjectProjectIDEnvironmentEnvironmentIDNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutProjectProjectIDEnvironmentEnvironmentIDParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PutProjectProjectIDEnvironmentEnvironmentID",
		Method:             "PUT",
		PathPattern:        "/project/{project_id}/environment/{environment_id}",
		ProducesMediaTypes: []string{"application/json", "text/plain; charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PutProjectProjectIDEnvironmentEnvironmentIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutProjectProjectIDEnvironmentEnvironmentIDNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutProjectProjectIDEnvironmentEnvironmentID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [VariableGroupParams].
	ctx context.Context
}
