// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInfoParams creates a new GetInfoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInfoParams() *GetInfoParams {
	return NewGetInfoParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetInfoParamsWithTimeout creates a new GetInfoParams object
// with the ability to set a timeout on a request.
func NewGetInfoParamsWithTimeout(timeout time.Duration) *GetInfoParams {
	return &GetInfoParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetInfoParamsWithContext creates a new GetInfoParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetInfoParams].
func NewGetInfoParamsWithContext(ctx context.Context) *GetInfoParams {
	return &GetInfoParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetInfoParamsWithHTTPClient creates a new GetInfoParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInfoParamsWithHTTPClient(client *http.Client) *GetInfoParams {
	return &GetInfoParams{
		HTTPClient: client,
	}
}

/*
GetInfoParams contains all the parameters to send to the API endpoint

	for the get info operation.

	Typically these are written to a http.Request.
*/
type GetInfoParams struct {
	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInfoParams) WithDefaults() *GetInfoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInfoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get info params.
func (o *GetInfoParams) WithTimeout(timeout time.Duration) *GetInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get info params.
func (o *GetInfoParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get info params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetInfoParams].
func (o *GetInfoParams) WithContext(ctx context.Context) *GetInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get info params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetInfoParams].
func (o *GetInfoParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get info params.
func (o *GetInfoParams) WithHTTPClient(client *http.Client) *GetInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get info params.
func (o *GetInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
