// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetEventsLastParams creates a new GetEventsLastParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetEventsLastParams() *GetEventsLastParams {
	return NewGetEventsLastParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetEventsLastParamsWithTimeout creates a new GetEventsLastParams object
// with the ability to set a timeout on a request.
func NewGetEventsLastParamsWithTimeout(timeout time.Duration) *GetEventsLastParams {
	return &GetEventsLastParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetEventsLastParamsWithContext creates a new GetEventsLastParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetEventsLastParams].
func NewGetEventsLastParamsWithContext(ctx context.Context) *GetEventsLastParams {
	return &GetEventsLastParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetEventsLastParamsWithHTTPClient creates a new GetEventsLastParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetEventsLastParamsWithHTTPClient(client *http.Client) *GetEventsLastParams {
	return &GetEventsLastParams{
		HTTPClient: client,
	}
}

/*
GetEventsLastParams contains all the parameters to send to the API endpoint

	for the get events last operation.

	Typically these are written to a http.Request.
*/
type GetEventsLastParams struct {
	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get events last params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEventsLastParams) WithDefaults() *GetEventsLastParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get events last params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEventsLastParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get events last params.
func (o *GetEventsLastParams) WithTimeout(timeout time.Duration) *GetEventsLastParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get events last params.
func (o *GetEventsLastParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get events last params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetEventsLastParams].
func (o *GetEventsLastParams) WithContext(ctx context.Context) *GetEventsLastParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get events last params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetEventsLastParams].
func (o *GetEventsLastParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get events last params.
func (o *GetEventsLastParams) WithHTTPClient(client *http.Client) *GetEventsLastParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get events last params.
func (o *GetEventsLastParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetEventsLastParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
