// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"terraform-provider-semaphoreui/semaphoreui/models"
)

// GetPingReader is a Reader for the GetPing structure.
type GetPingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetPingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /ping] GetPing", response, response.Code())
	}
}

// NewGetPingOK creates a GetPingOK with default headers values
func NewGetPingOK() *GetPingOK {
	return &GetPingOK{}
}

/*
GetPingOK describes a response with status code 200, with default header values.

Successful "PONG" reply
*/
type GetPingOK struct {
	ContentType string

	Payload models.Pong
}

// IsSuccess returns true when this get ping o k response has a 2xx status code
func (o *GetPingOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get ping o k response has a 3xx status code
func (o *GetPingOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get ping o k response has a 4xx status code
func (o *GetPingOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get ping o k response has a 5xx status code
func (o *GetPingOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get ping o k response a status code equal to that given
func (o *GetPingOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get ping o k response
func (o *GetPingOK) Code() int {
	return 200
}

func (o *GetPingOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ping][%d] getPingOK %s", 200, payload)
}

func (o *GetPingOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ping][%d] getPingOK %s", 200, payload)
}

func (o *GetPingOK) GetPayload() models.Pong {
	return o.Payload
}

func (o *GetPingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header content-type
	hdrContentType := response.GetHeader("content-type")

	if hdrContentType != "" {
		o.ContentType = hdrContentType
	}

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
