// Code generated by go-swagger; DO NOT EDIT.

package key_store

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewDeleteProjectProjectIDKeysKeyIDParams creates a new DeleteProjectProjectIDKeysKeyIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteProjectProjectIDKeysKeyIDParams() *DeleteProjectProjectIDKeysKeyIDParams {
	return NewDeleteProjectProjectIDKeysKeyIDParamsWithTimeout(cr.DefaultTimeout)
}

// NewDeleteProjectProjectIDKeysKeyIDParamsWithTimeout creates a new DeleteProjectProjectIDKeysKeyIDParams object
// with the ability to set a timeout on a request.
func NewDeleteProjectProjectIDKeysKeyIDParamsWithTimeout(timeout time.Duration) *DeleteProjectProjectIDKeysKeyIDParams {
	return &DeleteProjectProjectIDKeysKeyIDParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDeleteProjectProjectIDKeysKeyIDParamsWithContext creates a new DeleteProjectProjectIDKeysKeyIDParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteProjectProjectIDKeysKeyIDParams].
func NewDeleteProjectProjectIDKeysKeyIDParamsWithContext(ctx context.Context) *DeleteProjectProjectIDKeysKeyIDParams {
	return &DeleteProjectProjectIDKeysKeyIDParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDeleteProjectProjectIDKeysKeyIDParamsWithHTTPClient creates a new DeleteProjectProjectIDKeysKeyIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteProjectProjectIDKeysKeyIDParamsWithHTTPClient(client *http.Client) *DeleteProjectProjectIDKeysKeyIDParams {
	return &DeleteProjectProjectIDKeysKeyIDParams{
		HTTPClient: client,
	}
}

/*
DeleteProjectProjectIDKeysKeyIDParams contains all the parameters to send to the API endpoint

	for the delete project project ID keys key ID operation.

	Typically these are written to a http.Request.
*/
type DeleteProjectProjectIDKeysKeyIDParams struct {

	/* KeyID.

	   key ID
	*/
	KeyID int64

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the delete project project ID keys key ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectProjectIDKeysKeyIDParams) WithDefaults() *DeleteProjectProjectIDKeysKeyIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete project project ID keys key ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectProjectIDKeysKeyIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete project project ID keys key ID params.
func (o *DeleteProjectProjectIDKeysKeyIDParams) WithTimeout(timeout time.Duration) *DeleteProjectProjectIDKeysKeyIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete project project ID keys key ID params.
func (o *DeleteProjectProjectIDKeysKeyIDParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the delete project project ID keys key ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteProjectProjectIDKeysKeyIDParams].
func (o *DeleteProjectProjectIDKeysKeyIDParams) WithContext(ctx context.Context) *DeleteProjectProjectIDKeysKeyIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete project project ID keys key ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteProjectProjectIDKeysKeyIDParams].
func (o *DeleteProjectProjectIDKeysKeyIDParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the delete project project ID keys key ID params.
func (o *DeleteProjectProjectIDKeysKeyIDParams) WithHTTPClient(client *http.Client) *DeleteProjectProjectIDKeysKeyIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete project project ID keys key ID params.
func (o *DeleteProjectProjectIDKeysKeyIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKeyID adds the keyID to the delete project project ID keys key ID params.
func (o *DeleteProjectProjectIDKeysKeyIDParams) WithKeyID(keyID int64) *DeleteProjectProjectIDKeysKeyIDParams {
	o.SetKeyID(keyID)
	return o
}

// SetKeyID adds the keyId to the delete project project ID keys key ID params.
func (o *DeleteProjectProjectIDKeysKeyIDParams) SetKeyID(keyID int64) {
	o.KeyID = keyID
}

// WithProjectID adds the projectID to the delete project project ID keys key ID params.
func (o *DeleteProjectProjectIDKeysKeyIDParams) WithProjectID(projectID int64) *DeleteProjectProjectIDKeysKeyIDParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the delete project project ID keys key ID params.
func (o *DeleteProjectProjectIDKeysKeyIDParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DeleteProjectProjectIDKeysKeyIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param key_id
	if err := r.SetPathParam("key_id", conv.FormatInteger(o.KeyID)); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", conv.FormatInteger(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
