package provider

import (
	schemaR "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	superschema "github.com/orange-cloudavenue/terraform-plugin-framework-superschema"
)

type IntegrationAliasModel struct {
	ID            types.Int64  `tfsdk:"id"`
	ProjectID     types.Int64  `tfsdk:"project_id"`
	IntegrationID types.Int64  `tfsdk:"integration_id"`
	URL           types.String `tfsdk:"url"`
}

func IntegrationAliasSchema() superschema.Schema {
	return superschema.Schema{
		Common: superschema.SchemaDetails{
			MarkdownDescription: "An integration alias — a unique webhook URL that callers POST to in order to trigger the linked integration's template task.",
		},
		Resource: superschema.SchemaDetails{
			MarkdownDescription: "resource creates a SemaphoreUI integration alias (webhook URL). Aliases are immutable: changes to any attribute force the resource to be recreated.",
		},
		Attributes: map[string]superschema.Attribute{
			"id": superschema.Int64Attribute{
				Common: &schemaR.Int64Attribute{
					MarkdownDescription: "The alias ID.",
				},
				Resource: &schemaR.Int64Attribute{
					Computed:      true,
					PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()},
				},
			},
			"project_id": superschema.Int64Attribute{
				Common: &schemaR.Int64Attribute{
					MarkdownDescription: "The project ID this alias belongs to.",
					Required:            true,
				},
				Resource: &schemaR.Int64Attribute{
					PlanModifiers: []planmodifier.Int64{int64planmodifier.RequiresReplace()},
				},
			},
			"integration_id": superschema.Int64Attribute{
				Common: &schemaR.Int64Attribute{
					MarkdownDescription: "The integration this alias is bound to. When set, the alias only triggers the named integration. When omitted, the alias is project-scoped — incoming requests use SemaphoreUI's matcher rules to pick which integration to run.",
				},
				Resource: &schemaR.Int64Attribute{
					Optional:      true,
					PlanModifiers: []planmodifier.Int64{int64planmodifier.RequiresReplace()},
				},
			},
			"url": superschema.StringAttribute{
				Common: &schemaR.StringAttribute{
					MarkdownDescription: "The fully-qualified webhook URL callers POST to. Generated by SemaphoreUI at create time and immutable afterwards.",
				},
				Resource: &schemaR.StringAttribute{
					Computed:      true,
					PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				},
			},
		},
	}
}
