# Terraform Provider testing workflow.
name: Tests

# This GitHub action runs your tests for each pull request.
on:
  pull_request:
    branches-ignore:
      - 'release-please*'

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  # Ensure project builds before running tests
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v .
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12
          args: --tests=false

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      # We need the latest version of Terraform for our documentation generation to use
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: task generate
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'task generate' command and commit."; exit 1)

  # Run acceptance tests in a matrix with Semaphore UI versions
  test:
    name: Terraform Provider Acceptance Tests
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        semaphore:
          - 'v2.16.51'
          - 'v2.17.39'
          - 'v2.18.2'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: '1.15.x'
          terraform_wrapper: false
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: go mod download
      - run: task testacc
        env:
            SEMAPHORE_VERSION: ${{ matrix.semaphore }}
        timeout-minutes: 10

  # Wrapper job to allow us to require all tests in the matrix
  all-tests:
    name: Test Matrix
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: Check matrix status
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
